export const createArchivalDeliveryArguments = ({
  referencePath,
  soundtrackPath,
  outputPath,
}: Readonly<{
  referencePath: string;
  soundtrackPath: string;
  outputPath: string;
}>): readonly string[] => [
  '-hide_banner',
  '-i',
  referencePath,
  '-i',
  soundtrackPath,
  '-map',
  '0:v:0',
  '-map',
  '1:a:0',
  '-vf',
  [
    'scale=1080:1080',
    'flags=lanczos+accurate_rnd+full_chroma_inp+full_chroma_int',
    'in_range=tv',
    'out_range=tv',
    'in_color_matrix=bt709',
    'out_color_matrix=bt709',
  ].join(':') + ',format=yuv420p10le',
  '-c:v',
  'libx265',
  '-preset',
  'slow',
  '-crf',
  '18',
  '-x265-params',
  'colorprim=bt709:transfer=bt709:colormatrix=bt709:range=limited:repeat-headers=1',
  '-tag:v',
  'hvc1',
  '-color_primaries',
  'bt709',
  '-color_trc',
  'bt709',
  '-colorspace',
  'bt709',
  '-color_range',
  'tv',
  '-fps_mode',
  'passthrough',
  '-frames:v',
  '9180',
  '-c:a',
  'copy',
  '-movflags',
  '+faststart',
  '-metadata',
  'title=Tanisea — I’ll Scream to the Whole World',
  '-metadata:s:v:0',
  'handler_name=Tanisea English Lyric Film vNext',
  '-metadata:s:a:0',
  'handler_name=Original soundtrack — untouched AAC',
  '-y',
  outputPath,
];
