import {execFileSync} from 'node:child_process';
import {constants,copyFileSync,existsSync,readFileSync,statSync,writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {resolve} from 'node:path';
const output=resolve('../../outputs/Roi-x-Adore-Lyric-Film-Rebuilt-1080p60.mp4');
const desktop='<DELIVERY_DIRECTORY>/Roi-x-Adore-Lyric-Film-Rebuilt-1080p60.mp4';
const sha=(p:string)=>createHash('sha256').update(readFileSync(p)).digest('hex');
console.log('Encoding completed PNG frames as they become available.');
execFileSync(process.execPath,['scripts/encode-frames.ts','--stream'],{stdio:'inherit'});
while(!existsSync('../frames-v3-complete.json'))await new Promise(r=>setTimeout(r,100));
const render=JSON.parse(readFileSync('../frames-v3-complete.json','utf8'));
const probe=JSON.parse(execFileSync('ffprobe',['-v','error','-show_streams','-show_format','-of','json',output],{encoding:'utf8'}));
const video=probe.streams.find((s:{codec_type:string})=>s.codec_type==='video');
if(video.width!==1920||video.height!==1080||video.r_frame_rate!=='60/1'||video.codec_tag_string!=='hvc1'||video.pix_fmt!=='yuv420p10le')throw Error('Unexpected delivery format');
if(video.color_space!=='bt709'||video.color_transfer!=='bt709'||video.color_primaries!=='bt709')throw Error('Incomplete BT.709 metadata');
console.log('Decoding every frame and audio packet.');
execFileSync('ffmpeg',['-v','error','-xerror','-err_detect','explode','-i',output,'-progress','../decode-progress.txt','-f','null','-'],{stdio:'inherit'});
const decode=readFileSync('../decode-progress.txt','utf8');
const counts=[...decode.matchAll(/^frame=(\d+)$/gm)].map(m=>Number(m[1]));
if(counts.at(-1)!==22763)throw Error('Decoded frame-count mismatch');
const audioHash=(path:string)=>execFileSync('ffmpeg',['-v','error','-i',path,'-map','0:a:0','-c','copy','-f','hash','-hash','sha256','-'],{encoding:'utf8'}).trim();
const sourceAudio=audioHash('public/soundtrack.m4a'),finalAudio=audioHash(output);
if(sourceAudio!==finalAudio)throw Error('AAC packets changed');
const hash=sha(output);
if(existsSync(desktop)){if(sha(desktop)!==hash)throw Error('A different file already occupies the Desktop destination');}
else copyFileSync(output,desktop,constants.COPYFILE_EXCL);
if(sha(desktop)!==hash)throw Error('Desktop copy verification failed');
const report={file:output.split('/').at(-1),bytes:statSync(output).size,sha256:hash,video,fullDecode:'passed',decodedFrames:counts.at(-1),audioPacketsIdentical:true,audioHash:finalAudio,desktopCopyVerified:true,render,checks:JSON.parse(readFileSync('../checks.json','utf8')),spectrumCalibration:JSON.parse(readFileSync('analysis/calibration.json','utf8')),independentCalibration:JSON.parse(readFileSync('analysis/independent-calibration.json','utf8')),motion:JSON.parse(readFileSync('analysis/motion-manifest.json','utf8'))};
writeFileSync('../../outputs/Roi-x-Adore-Verification.json',JSON.stringify(report,null,2));
writeFileSync('../delivery-complete.json',JSON.stringify({file:output,desktop,sha256:hash}));
console.log('DELIVERY_COMPLETE '+JSON.stringify({desktop,sha256:hash}));
