import {createWorld} from './scene.js';
import {makeTypography} from './typography.js';
import {featuresAt,frameState,cueAt,CHAPTERS,clamp} from './core.js';
const $=s=>document.querySelector(s),audio=$('#audio'),stage=$('#stage'),seek=$('#seek');
const storageKey='leave-it-on-preview-v1-notes';let notes=[];try{notes=JSON.parse(localStorage.getItem(storageKey)||'[]')}catch{}
let world,lyrics,features,spectrum,format='portrait',raf=0,ready=false,lastCue='',frameCount=0,lastDrawTime=-1,generation=0;
const restoreButton=$('#restore');let initializing=true,restoring=false,restoreRequest=0;restoreButton.disabled=true;
const type=makeTypography($('#type'));
const fmt=t=>`${Math.floor(t/60)}:${String(Math.floor(t%60)).padStart(2,'0')}`;
function error(e){$('#error').hidden=false;$('#error').textContent=`Preview needs attention: ${e?.message||e}. Use Restore visuals; if it persists, restart with npm run preview and check the local source/assets.`;$('#load-detail').textContent=e?.message||String(e)}
const settings=()=>({effects:$('#effects').checked,reduced:$('#reduced').checked,lyrics:$('#lyrics-toggle').checked});
function draw(){if(!ready||!world)return;const t=audio.currentTime;const state=frameState(t,featuresAt(features,t),{...settings(),cues:lyrics.cues});world.setOptions(settings());world.update(state);type.draw(t,lyrics,state,{...settings(),lyrics:false});const out=world.lyricState;stage.dataset.time=t.toFixed(3);stage.dataset.frames=String(frameCount);stage.dataset.cue=out.cue?.id||'';stage.dataset.activeWord=out.geometry.find(w=>w.active)?.text||'';stage.dataset.lyricCorners=JSON.stringify(out.projectedCorners||[]);stage.dataset.ready='true';lastDrawTime=t;frameCount++;seek.value=t;$('#current').textContent=fmt(t);const chapter=CHAPTERS.findLast(c=>c.t<=t)||CHAPTERS[0];$('#now-playing').textContent=chapter.label;document.querySelectorAll('.chapter').forEach((b,i)=>b.classList.toggle('active',chapter===CHAPTERS[i]));const id=out.cue?.id||'';if(id!==lastCue){lastCue=id;$('#cue-status').textContent=out.cue?`${out.cue.id} · ${out.cue.requiresReview?'Listening review pending':'Acoustic candidate'} · ${out.cue.text}`:'Instrumental / between lyric cues';}}
function stopPump(){generation++;if(raf)cancelAnimationFrame(raf);raf=0}
function pump(){stopPump();const g=generation;function frame(){if(g!==generation)return;draw();if(!audio.paused&&!audio.ended)raf=requestAnimationFrame(frame);else raf=0}raf=requestAnimationFrame(frame)}
function settled(){draw();const g=generation;requestAnimationFrame(()=>{if(g===generation)draw()})}
function resize(){if(!world)return;const r=stage.getBoundingClientRect();world.resize(Math.round(r.width),Math.round(r.height),format);type.resize(format);settled()}
async function setTime(t){audio.currentTime=clamp(t,0,Number.isFinite(audio.duration)?audio.duration:273.56);settled()}
async function setFormat(f){format=f;stage.className=f;document.querySelectorAll('[data-format]').forEach(b=>b.classList.toggle('selected',b.dataset.format===f));resize()}
async function auditLayout(){const results=[];const previousFormat=format;for(const f of ['portrait','landscape']){await setFormat(f);for(const cue of lyrics.cues){for(const t of [cue.start+.001,(cue.start+cue.end)/2,cue.end-.001]){world.update(frameState(t,featuresAt(features,t),{...settings(),cues:lyrics.cues}));const out=world.lyricState;const b=out.projectedCorners;results.push({format:f,id:cue.id,t:Number(t.toFixed(3)),bounds:b,pass:b.length===2&&b[0][0]>=-.91&&b[1][0]<=.91&&b[0][1]>=-.8&&b[1][1]<=.85,atlasPass:out.geometry.every(w=>w.y-w.ascent-12>=0&&w.y+w.descent+12<=896)});}}}await setFormat(previousFormat);draw();const audit={samples:results.length,failed:results.filter(x=>!x.pass||!x.atlasPass),minimumX:Math.min(...results.map(x=>x.bounds[0]?.[0]??0)),maximumX:Math.max(...results.map(x=>x.bounds[1]?.[0]??0))};stage.dataset.layoutAudit=JSON.stringify(audit);return audit}
async function saveStill(){const playing=!audio.paused;audio.pause();const w=format==='portrait'?1080:1920,h=format==='portrait'?1920:1080;world.resize(w,h,format);type.resize(format);draw();const shot=document.createElement('canvas');shot.width=w;shot.height=h;const context=shot.getContext('2d');context.drawImage($('#scene'),0,0,w,h);context.drawImage($('#type'),0,0,w,h);const name=`preview-${format}-${audio.currentTime.toFixed(3)}.png`;const response=await fetch('/__review/still',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,png:shot.toDataURL('image/png')})});if(!response.ok)throw Error('Could not save review still');stage.dataset.savedStill=(await response.json()).path;resize();if(playing)await audio.play();return name}
function renderNotes(){$('#notes').replaceChildren();$('#note-count').textContent=notes.length;for(const note of notes){const div=document.createElement('div');div.className='note-entry';const button=document.createElement('button');button.textContent=fmt(note.time);button.onclick=()=>setTime(note.time);div.append(button,document.createTextNode(note.text));$('#notes').append(div)}}
stage.addEventListener('click',e=>{const link=world?.pickLink(e.clientX,e.clientY);if(link)window.open(link,'_blank','noopener,noreferrer')});stage.addEventListener('pointermove',e=>{stage.style.cursor=world?.pickLink(e.clientX,e.clientY)?'pointer':'default'});
$('#play').onclick=async()=>{if(!ready)return;try{if(audio.paused){if(audio.ended)audio.currentTime=0;await audio.play()}else audio.pause()}catch(e){error(e)}};
$('#restart').onclick=()=>setTime(0);seek.oninput=()=>setTime(Number(seek.value));$('#speed').onchange=()=>{audio.playbackRate=Number($('#speed').value);settled()};$('#mute').onclick=()=>{audio.muted=!audio.muted;$('#mute').textContent=audio.muted?'Sound off':'Sound on'};
document.querySelectorAll('[data-format]').forEach(b=>b.onclick=()=>setFormat(b.dataset.format));
for(const id of ['reduced','effects','lyrics-toggle'])$('#'+id).onchange=settled;
$('#fullscreen').onclick=()=>{document.body.classList.toggle('cinema');$('#fullscreen').textContent=document.body.classList.contains('cinema')?'Exit cinema ↙':'Cinema view ↗';requestAnimationFrame(resize)};
$('#prev-cue').onclick=()=>{const cues=lyrics.cues.filter(c=>c.start<audio.currentTime-.5);setTime(cues.at(-1)?.start||0)};$('#next-cue').onclick=()=>setTime(lyrics.cues.find(c=>c.start>audio.currentTime+.1)?.start||audio.duration);
$('#save-note').onclick=()=>{const text=$('#note').value.trim();if(!text)return;notes.push({time:audio.currentTime,format,cueId:cueAt(lyrics.cues,audio.currentTime)?.id||null,text,revision:'preview-v2-pr375'});localStorage.setItem(storageKey,JSON.stringify(notes));$('#note').value='';renderNotes()};
$('#export-notes').onclick=()=>{const blob=new Blob([JSON.stringify({revision:'preview-v2-pr375',notes},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='leave-it-on-review-notes.json';a.click();URL.revokeObjectURL(a.href)};
restoreButton.onclick=async()=>{
 if(initializing||restoring)return;
 restoring=true;restoreButton.disabled=true;const request=++restoreRequest;
 const playing=!audio.paused,pos=audio.currentTime;audio.pause();ready=false;stopPump();$('#loading').hidden=false;
 try{
  const previous=world;world=null;previous?.dispose();
  const old=$('#scene'),canvas=document.createElement('canvas');canvas.id='scene';old.replaceWith(canvas);
  const replacement=await createWorld(canvas,text=>{if(request===restoreRequest)$('#load-detail').textContent=text});
  if(request!==restoreRequest){replacement.dispose();return;}
  replacement.setData(lyrics,spectrum);world=replacement;audio.currentTime=pos;ready=true;resize();$('#error').hidden=true;
  if(playing)await audio.play();else settled();
 }catch(e){if(request===restoreRequest)error(e)}
 finally{if(request===restoreRequest){restoring=false;restoreButton.disabled=false;$('#loading').hidden=true}}
};
audio.addEventListener('play',()=>{$('#play').innerHTML='Pause film <span>Ⅱ</span>';pump()});audio.addEventListener('pause',()=>{$('#play').innerHTML='Play film <span>▶</span>';stopPump();settled()});audio.addEventListener('seeking',()=>{stopPump();settled()});audio.addEventListener('seeked',()=>{settled();if(!audio.paused)pump()});audio.addEventListener('ended',()=>{stopPump();settled()});audio.addEventListener('loadedmetadata',()=>{seek.max=audio.duration;$('#duration').textContent=fmt(audio.duration)});audio.addEventListener('error',()=>error(new Error(`Audio could not load (${audio.error?.message||audio.error?.code}). Restore the original local audio or WebM stream copy.`)));
document.addEventListener('visibilitychange',()=>{if(document.hidden)stopPump();else{settled();if(!audio.paused)pump()}});window.addEventListener('resize',resize);new ResizeObserver(resize).observe(stage);
window.addEventListener('keydown',e=>{if(/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;if(e.code==='Space'){e.preventDefault();$('#play').click()}if(e.key==='ArrowRight')setTime(audio.currentTime+5);if(e.key==='ArrowLeft')setTime(audio.currentTime-5);if(e.key==='Escape'&&document.body.classList.contains('cinema'))$('#fullscreen').click()});
for(const [i,c] of CHAPTERS.entries()){const b=document.createElement('button');b.className='chapter';b.innerHTML=`<span class="idx">${String(i+1).padStart(2,'0')}</span><span class="chapter-title">${c.label}</span><time>${fmt(c.t)}</time>`;b.onclick=()=>setTime(c.t);$('#chapters').append(b)}
renderNotes();
try{await document.fonts.ready;const responses=await Promise.all(['/data/lyrics.json','/data/features.json','/data/spectrum.json'].map(async u=>{const r=await fetch(u);if(!r.ok)throw Error(`${u} is missing (${r.status})`);return r.json()}));[lyrics,features,spectrum]=responses;world=await createWorld($('#scene'),text=>$('#load-detail').textContent=text);world.setData(lyrics,spectrum);ready=true;const params=new URLSearchParams(location.search);if(params.has('cinema'))document.body.classList.add('cinema');await setFormat(params.get('format')==='landscape'?'landscape':'portrait');$('#loading').hidden=true;audio.pause();audio.currentTime=Number(params.get('t')||0);settled();if(params.has('layoutaudit'))await auditLayout();if(params.has('capture'))requestAnimationFrame(()=>requestAnimationFrame(()=>saveStill().catch(error)));}catch(e){error(e)}finally{initializing=false;restoreButton.disabled=false}
window.leaveItOn={seek:setTime,setFormat,draw,restore:()=>$('#restore').click(),get state(){return {ready,time:audio.currentTime,duration:audio.duration,format,frameCount,lastDrawTime,paused:audio.paused,cue:cueAt(lyrics?.cues||[],audio.currentTime),geometry:world?.lyricState?.geometry,scene:world?.state,stats:world?.stats,bounds:world?.bounds,notes}},get world(){return world}};
