import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {createReadStream,readFileSync,readdirSync,writeFileSync} from 'node:fs';
const hash=async(path:string)=>{const h=createHash('sha256');for await(const b of createReadStream(path))h.update(b);return h.digest('hex');};
const oldRoot='evidence/cinematic/original-capture';
const oldScript=readFileSync(oldRoot+'/render-cinematic.ts.txt','utf8');
const expected=oldScript.replace("'-fps_mode','passthrough',output]","'-fps_mode','cfr',output]").replace(
 'const outcomes=await Promise.allSettled(kinds.map(kind=>renderFormat(kind).catch(e=>{stop();throw e;})));',
 'let initialError:unknown;\nconst outcomes=await Promise.allSettled(kinds.map(kind=>renderFormat(kind).catch(e=>{initialError??=e;stop();throw e;})));\nif(initialError!==undefined)throw initialError;');
assert.equal(readFileSync('scripts/render-cinematic.ts','utf8'),expected,'Only the audited assembly/error-report changes may reuse capture receipts');
const oldManifest=JSON.parse(readFileSync(oldRoot+'/render-inputs.json','utf8'));
const newManifest=JSON.parse(readFileSync('evidence/render-inputs.json','utf8'));
const withoutOrchestrator=(data:{inputs:{path:string;sha256:string}[]})=>data.inputs.filter(input=>input.path!=='scripts/render-cinematic.ts');
assert.deepEqual(withoutOrchestrator(oldManifest),withoutOrchestrator(newManifest),'A visual, source, timing, layout or dependency input changed');
for(const input of newManifest.inputs)assert.equal(await hash(input.path),input.sha256,'Current frozen input differs');
const oldHash=await hash(oldRoot+'/render-inputs.json'),newHash=await hash('evidence/render-inputs.json');
const oldScriptHash=await hash(oldRoot+'/render-cinematic.ts.txt');
const migrated=[];
for(const file of readdirSync(oldRoot).filter(name=>/^(youtube|tiktok)-part-\d.json$/.test(name))){
 const receipt=JSON.parse(readFileSync(oldRoot+'/'+file,'utf8'));
 assert.equal(receipt.frozenInputManifestSha256,oldHash);
 assert.equal(await hash(receipt.output),receipt.sha256,'Completed capture bytes changed');
 const previousReceiptSha256=await hash(oldRoot+'/'+file);
 receipt.frozenInputManifestSha256=newHash;
 receipt.reusedCapture={originalFrozenInputManifestSha256:oldHash,originalRenderScriptSha256:oldScriptHash,originalReceiptSha256:previousReceiptSha256,reason:'Only final full-frame FFmpeg assembly changed from conflicting rate/passthrough flags to CFR; error reporting also preserves the initial cause. Browser capture, codec settings, frame ranges and all image/timing/source inputs are byte-identical.'};
 writeFileSync('evidence/cinematic/'+file,JSON.stringify(receipt,null,2));
 migrated.push({file,output:receipt.output,sha256:receipt.sha256,originalReceiptSha256:previousReceiptSha256});
}
writeFileSync('evidence/cinematic/capture-reuse.json',JSON.stringify({passed:true,originalFrozenInputManifestSha256:oldHash,currentFrozenInputManifestSha256:newHash,originalRenderScriptSha256:oldScriptHash,currentRenderScriptSha256:await hash('scripts/render-cinematic.ts'),allNonOrchestrationInputsIdentical:true,originalRecords:oldRoot,migrated,scope:'No captured frame is changed or generated by this receipt migration; completed lossless captures are reused after a final assembly command correction.'},null,2));
console.log({reusedCompletedChunks:migrated.length,allNonOrchestrationInputsIdentical:true});
