import {execFileSync} from 'node:child_process';
import {cpSync,mkdirSync,readdirSync,statSync,writeFileSync,createReadStream,existsSync} from 'node:fs';
import {join,resolve,relative} from 'node:path';
import {createHash} from 'node:crypto';
import assert from 'node:assert/strict';
const repo=resolve(process.env.LYRICS_REPO??'../lyrics'),commit=execFileSync('git',['-C',repo,'rev-parse','HEAD']).toString().trim();
const root=resolve('package/Midnight-Love-Complete-Production');
assert(!existsSync(root),'Use a fresh package directory to avoid retaining stale assets.');
mkdirSync(root,{recursive:true});mkdirSync('release',{recursive:true});
execFileSync('git',['-C',repo,'archive','--format=tar',`--output=${resolve('package/source.tar')}`,commit,'projects/midnight-love-lyric-film']);
execFileSync('tar',['-xf','package/source.tar','--strip-components=2','-C',root]);
for(const dir of ['source','public','analysis','output'])mkdirSync(join(root,dir),{recursive:true});
for(const p of ['original.mkv','soundtrack.opus','original.en-orig.json3'])cpSync('source/'+p,join(root,'source',p));
cpSync('source.json',join(root,'source/source-metadata.json'));
for(const p of ['source-video.webm','soundtrack.m4a'])cpSync('public/'+p,join(root,'public',p));
cpSync('analysis/stems',join(root,'analysis/stems'),{recursive:true});
cpSync('analysis/bands-dbfs.f32',join(root,'analysis/bands-dbfs.f32'));
cpSync('output',join(root,'output'),{recursive:true});
cpSync('evidence/encoded',join(root,'evidence/encoded'),{recursive:true});
cpSync('evidence/Midnight-Love-Smooth-Preview.mp4',join(root,'evidence/Midnight-Love-Smooth-Preview.mp4'));
cpSync('evidence/Midnight-Love-Opening-Preview.mp4',join(root,'evidence/Midnight-Love-Opening-Preview.mp4'));
writeFileSync(join(root,'SOURCE-REVISION.txt'),commit+'\n');
for(const name of ['LICENSE.md','AI-DISCLOSURE.md','CREDITS.md'])cpSync(join(repo,name),join(root,'REPOSITORY-'+name));
cpSync(join(repo,'LICENSES'),join(root,'LICENSES'),{recursive:true});
const hash=async(p:string)=>{const h=createHash('sha256');for await(const b of createReadStream(p))h.update(b);return h.digest('hex');};
const files:string[]=[];const walk=(d:string)=>{for(const e of readdirSync(d,{withFileTypes:true})){const p=join(d,e.name);if(e.isDirectory())walk(p);else if(e.isFile())files.push(p);else throw Error('Unexpected non-regular package entry '+p);}};walk(root);
const entries=[];for(const p of files.sort())entries.push({path:relative(root,p),bytes:statSync(p).size,sha256:await hash(p)});
writeFileSync(join(root,'MANIFEST.json'),JSON.stringify({sourceCommit:commit,files:entries},null,2));
writeFileSync(join(root,'CHECKSUMS.sha256'),entries.map(e=>`${e.sha256}  ${e.path}\n`).join(''));
execFileSync('zip',['-q','-r','-6',resolve('release/Midnight-Love-Complete-Production.zip'),'Midnight-Love-Complete-Production'],{cwd:resolve('package')});
execFileSync('unzip',['-tq','release/Midnight-Love-Complete-Production.zip']);
for(const p of readdirSync('output'))cpSync('output/'+p,'release/'+p);
cpSync('source/original.mkv','release/Midnight-Love-Original-Source.mkv');
cpSync('analysis/cover-prompts.json','release/Midnight-Love-Cover-Prompts.json');
const releaseEntries=[];
for(const p of readdirSync('release').filter(p=>p!=='CHECKSUMS.sha256'&&p!=='release-assets.json').sort())releaseEntries.push({file:p,bytes:statSync('release/'+p).size,sha256:await hash('release/'+p)});
writeFileSync('release/CHECKSUMS.sha256',releaseEntries.map(e=>`${e.sha256}  ${e.file}\n`).join(''));
writeFileSync('release/release-assets.json',JSON.stringify({sourceCommit:commit,assets:releaseEntries},null,2));
console.log({sourceCommit:commit,productionFiles:entries.length,releaseAssets:releaseEntries.length});
