import {readFileSync,writeFileSync} from 'node:fs';
import assert from 'node:assert/strict';
const record=(v:unknown):Record<string,unknown>=>{assert(v&&typeof v==='object'&&!Array.isArray(v));return v as Record<string,unknown>;};
const text=(v:unknown):string=>{assert.equal(typeof v,'string');return v as string;};
const number=(v:unknown):number=>{assert(typeof v==='number'&&Number.isFinite(v));return v;};
const films=['youtube','tiktok'].map(kind=>{
 const v=record(JSON.parse(readFileSync(`evidence/${kind}-verification.json`,'utf8'))),video=record(v.video);
 assert.equal(v.strictFullDecodePassed,true);assert.equal(v.aacPacketIdentity,true);
 return {file:text(v.file),bytes:number(v.bytes),sha256:text(v.sha256),aacPacketCount:number(v.aacPacketCount),video:{width:number(video.width),height:number(video.height),nb_read_frames:text(video.nb_read_frames),avg_frame_rate:text(video.avg_frame_rate)}};
});
const reviewed=record(JSON.parse(readFileSync('evidence/encoded-frame-review.json','utf8')));assert.equal(reviewed.status,'Selected decoded frames visually reviewed');
const viewport=record(JSON.parse(readFileSync('evidence/viewport-proof.json','utf8')));assert.equal(viewport.passed,true);
const pixels=record(JSON.parse(readFileSync('evidence/cinematic-pixel-verification.json','utf8')));assert.equal(pixels.passed,true);
const first=films[0];assert(first);
const rows=films.map(v=>`| ${v.file} | ${v.video.width}×${v.video.height} | ${v.video.nb_read_frames} | ${v.video.avg_frame_rate} | ${(v.bytes/1e6).toFixed(1)} MB |`).join('\n');
writeFileSync('evidence/final-verification.md',`# Delivery verification\n\n| File | Dimensions | Decoded frames | Frame rate | Size |\n| --- | --- | --- | --- | --- |\n${rows}\n\nBoth movies passed complete strict decoding. They contain identical locked AAC packets and timestamps (${first.aacPacketCount.toLocaleString('en-US')} packets per film), 48 kHz stereo audio, H.264 High video, square pixels, limited-range BT.709 tags and fast-start MP4 metadata. Video duration is 193.866667 seconds; retained source audio is 193.8535 seconds.\n\nAll 38 cues and 185 performed words passed coverage, ordering, positive-interval and focus-group checks. This retains all 151 supplied words and restores 34 repeated words in six ending cues. The 161 focus groups are shared by both formats, and each is fully visible on its first focus frame. Maximum nearest-frame quantization is 8.3125 ms. All 152 active/inactive layout states fit their safe areas without highlight-induced glyph movement. Eleven source-versus-AAC correlation windows measured zero lag.\n\nFrame quantization is not acoustic accuracy. Full and bounded attention, mix/vocal MMS and an independent English acoustic encoder inform the timing. Short vowels, held endings and the second chorus around 105.6 s retain uncertainty. The restored ending is independently corroborated by blind mix/vocal transcription and bounded acoustic passes. The final sustained vowel is held until approximately 185.4 s; this endpoint is an estimate, not a calibrated ground-truth boundary. Earlier But focus and Able onset were also corrected with documented acoustic evidence. Repeated-phrase waveform searches did not justify copying cue times. No human/native-listener audition is claimed.\n\nThe complete lyric treatment uses stable color-only emphasis throughout; active-word underlines are removed. Sixteen sampled 2× PNG viewports match the corresponding full-composition crops exactly. Separate lossless decoded-frame comparisons verify that the rebuilt reading area matches its new viewport and the surrounding pixels match the original master, including chunk joins and corrected lyric passages. These are sampled proofs, not exhaustive per-pixel checks of every frame. See viewport-proof.json and cinematic-pixel-verification.json. Selected final decoded frames cover the intro, lyric passages, rendering chunk boundaries, restored ending cues, sustained release and closing fade. The continuous grading has no cue-shaped panel; the portrait artwork fades before its lower boundary. See encoded-frame-review.json for reviewed indices and observations.\n\nThe original source is nominally 24 fps. Added camera movement, words, embers and measured spectrum are rendered on the 60 fps clock; original animation detail is not interpolated or invented.\n\n## SHA-256\n\n${films.map(v=>`\`${v.sha256}\` — ${v.file}`).join('\n\n')}\n`);
