import {readFileSync,writeFileSync} from 'node:fs';
import assert from 'node:assert/strict';
const record=(v:unknown):Record<string,unknown>=>{assert(v&&typeof v==='object'&&!Array.isArray(v));return v as Record<string,unknown>;};
const text=(v:unknown):string=>{assert.equal(typeof v,'string');return v as string;};
const number=(v:unknown):number=>{assert(typeof v==='number'&&Number.isFinite(v));return v;};
const films=['youtube','tiktok'].map(kind=>{
 const v=record(JSON.parse(readFileSync(`evidence/${kind}-verification.json`,'utf8'))),video=record(v.video);
 assert.equal(v.strictFullDecodePassed,true);assert.equal(v.aacPacketIdentity,true);
 return {file:text(v.file),bytes:number(v.bytes),sha256:text(v.sha256),aacPacketCount:number(v.aacPacketCount),video:{width:number(video.width),height:number(video.height),nb_read_frames:text(video.nb_read_frames),avg_frame_rate:text(video.avg_frame_rate)}};
});
const reviewed=record(JSON.parse(readFileSync('evidence/encoded-frame-review.json','utf8')));assert.equal(reviewed.status,'Selected decoded frames visually reviewed');
const first=films[0];assert(first);
const rows=films.map(v=>`| ${v.file} | ${v.video.width}×${v.video.height} | ${v.video.nb_read_frames} | ${v.video.avg_frame_rate} | ${(v.bytes/1e6).toFixed(1)} MB |`).join('\n');
writeFileSync('evidence/final-verification.md',`# Delivery verification\n\n| File | Dimensions | Decoded frames | Frame rate | Size |\n| --- | --- | --- | --- | --- |\n${rows}\n\nBoth movies passed complete strict decoding. They contain identical locked AAC packets and timestamps (${first.aacPacketCount.toLocaleString('en-US')} packets per film), 48 kHz stereo audio, H.264 High video, square pixels, limited-range BT.709 tags and fast-start MP4 metadata. Video duration is 193.866667 seconds; retained source audio is 193.8535 seconds.\n\nAll 32 cues and 151 supplied words passed coverage, ordering, positive-interval and focus-group checks. The 132 focus groups are shared by both formats. Maximum nearest-frame quantization is 8.3125 ms. All 128 active/inactive layout states fit their safe areas without highlight-induced glyph movement. Eleven source-versus-AAC correlation windows measured zero lag.\n\nFrame quantization is not acoustic accuracy. Full and bounded attention, mix/vocal MMS and an independent English acoustic encoder inform the timing. Short vowels, held endings and the second chorus around 105.6 s retain uncertainty. Repeated-phrase waveform searches did not justify copying cue times. No human/native-listener audition is claimed.\n\nSelected final decoded frames cover the intro, lyric passages, both sides of the 96.933333-second segment join, sustained endings, instrumental tail and fade. The continuous grading has no cue-shaped panel; the portrait artwork fades before its lower boundary. See encoded-frame-review.json for reviewed indices and observations.\n\nThe original source is nominally 24 fps. Added camera movement, words, embers and measured spectrum are rendered on the 60 fps clock; original animation detail is not interpolated or invented.\n\n## SHA-256\n\n${films.map(v=>`\`${v.sha256}\` — ${v.file}`).join('\n\n')}\n`);
