import {spawn} from 'node:child_process';import {readFileSync,writeFileSync,createReadStream} from 'node:fs';import {createHash} from 'node:crypto';import {basename} from 'node:path';
import {GlobalFonts,createCanvas} from '@napi-rs/canvas';import {rawFrames} from './frame-io.ts';import {parseData,type Format} from '../src/schema.ts';import type {Layouts} from '../src/layout-types.ts';import {visibleCues,activeSource} from '../src/focus.ts';
const file=process.argv[2],format=process.argv[3] as Format;if(!file||!['landscape','portrait'].includes(format))throw Error('Usage: file landscape|portrait');
const read=(p:string)=>JSON.parse(readFileSync(p,'utf8')),data=parseData(read('src/cues.json')),l=(read('src/layout.json') as Layouts)[format],masks=new Map<string,number[]>();GlobalFonts.registerFromPath('public/SpaceGrotesk.ttf','StaySans');
const all=Object.values(l.cues).flatMap(c=>c.source),maxFont=Math.max(...Object.values(l.cues).map(c=>c.fontSize));const x=Math.max(0,Math.floor(Math.min(...all.map(w=>w.x)))-8),y=Math.floor(Math.min(...all.map(w=>w.y))-maxFont*1.5),width=Math.min(l.width-x,Math.ceil(Math.max(...all.map(w=>w.x+w.width))-x+8)),height=Math.min(l.height-y,Math.ceil(Math.max(...all.map(w=>w.y))-y+maxFont*.5));
for(const cue of data.cues){const cl=l.cues[cue.id]!;for(const word of cl.source){const size=cl.fontSize,canvas=createCanvas(Math.ceil(word.width+10),Math.ceil(size*1.5)),ctx=canvas.getContext('2d');ctx.font=`600 ${size}px StaySans`;ctx.fillStyle='white';ctx.fillText(word.text,word.x-Math.floor(word.x)+3,size);const rgba=ctx.getImageData(0,0,canvas.width,canvas.height).data,inside=(px:number,py:number)=>rgba[(py*canvas.width+px)*4+3]!>=254,points:number[]=[];
 for(let py=2;py<canvas.height-2;py++)for(let px=2;px<canvas.width-2;px++)if(inside(px,py)&&inside(px-1,py)&&inside(px+1,py)&&inside(px,py-1)&&inside(px,py+1)){const gx=Math.floor(word.x)-3+px,gy=Math.round(word.y-size)+py;if(gx>=x&&gx<x+width&&gy>=y&&gy<y+height)points.push(((gy-y)*width+gx-x)*3);}
 if(points.length<4)throw Error('Insufficient glyph interior '+word.id);const n=Math.min(50,points.length);masks.set(word.id,Array.from({length:n},(_,i)=>points[Math.floor(i*points.length/n)]!));
}}
const child=spawn('ffmpeg',['-v','error','-threads','2','-i',file,'-an','-vf',`crop=${width}:${height}:${x}:${y}:exact=1`,'-pix_fmt','rgb24','-fps_mode','passthrough','-f','rawvideo','pipe:1'],{stdio:['ignore','pipe','inherit']});const done=new Promise<void>((resolve,reject)=>child.once('close',code=>code===0?resolve():reject(Error('Decode failed'))));void done.catch(()=>{});
const activeColor=[252,238,10],idleColor=[241,243,237];let frames=0,wordStates=0,ambiguous=0,mismatchCount=0;const failures:any[]=[];
for await(const buffer of rawFrames(child.stdout,width*height*3)){
 for(const cue of visibleCues(data,frames)){const active=activeSource(cue,frames,data);for(const word of cue.source){const points=masks.get(word.id)!,color=[0,1,2].map(channel=>{const values=points.map(p=>buffer[p+channel]!).sort((a,b)=>a-b);return values[Math.floor(values.length/2)]!;}),distance=(target:number[])=>Math.hypot(...color.map((v,i)=>v-target[i]!)),toActive=distance(activeColor),toIdle=distance(idleColor);if(Math.min(toActive,toIdle)>40||Math.abs(toActive-toIdle)<40){ambiguous++;if(failures.length<50)failures.push({frame:frames,word:word.id,type:'ambiguous',color});}else if((toActive<toIdle)!==active.has(word.id)){mismatchCount++;if(failures.length<50)failures.push({frame:frames,word:word.id,type:'wrong focus',color});}wordStates++;}}
 frames++;
}
await done;if(frames!==data.frames)throw Error('Incomplete final frame inventory');const hash=createHash('sha256');for await(const b of createReadStream(file))hash.update(b);const report={status:failures.length?'failed':'passed',inputFile:basename(file),inputSha256:hash.digest('hex'),format,decodedFrames:frames,wordStates,ambiguous,mismatchCount,failures,method:'Every visible word in every decoded frame, sampled inside eroded bundled-font glyph masks; median RGB distance classifies yellow focus versus ivory resting text. Checks the encoded display against the frozen cue intervals, not acoustic truth.'};writeFileSync(`evidence/focus-${format}.json`,JSON.stringify(report,null,2)+'\n');console.log(report);if(failures.length)process.exitCode=1;
