import {spawn} from 'node:child_process';import {readFileSync,writeFileSync,createReadStream} from 'node:fs';import {createHash} from 'node:crypto';import {basename} from 'node:path';import {createCanvas,loadImage,GlobalFonts,ImageData} from '@napi-rs/canvas';
import {drawScene} from '../src/scene.ts';import {parseData,type Format} from '../src/schema.ts';import {montages} from '../src/trailer.ts';import {rawFrames,decodeVideo} from './frame-io.ts';
const file=process.argv[2],format=process.argv[3] as Format;if(!file||!['landscape','portrait'].includes(format))throw Error('Usage: video landscape|portrait');
const read=(p:string)=>JSON.parse(readFileSync(p,'utf8')),data=parseData(read('src/cues.json')),layouts=read('src/layout.json'),bands=read('public/science.json'),motion=read('public/motion.json'),p=format==='portrait',crop=p?{x:80,y:380,w:920,h:600}:{x:1240,y:100,w:600,h:700},size=96;
GlobalFonts.registerFromPath('public/SpaceGrotesk.ttf','StaySans');GlobalFonts.registerFromPath('public/Oswald-Bold.ttf','StayDisplay');const canvas=createCanvas(size,size),ctx=canvas.getContext('2d'),video=createCanvas(1920,1080),vctx=video.getContext('2d'),art=await loadImage('public/source-artwork.png');ctx.scale(size/crop.w,size/crop.h);ctx.translate(-crop.x,-crop.y);
const expected:Buffer[]=[],critical=new Map<number,string[]>();for(const m of montages)for(const s of m.shots){const base=Math.round(m.songStart*60)+s.startFrame;for(const [f,name] of [[base,'cut'],...('accents' in s?s.accents:('accent' in s&&s.accent?[s.accent]:[])).map(a=>[base+a.frame,'action'])] as [number,string][]){critical.set(f,[...(critical.get(f)??[]),`${m.id}/${s.name}/${name}`]);}}
let deck:ReturnType<typeof decodeVideo>|undefined;for(let f=0;f<data.frames;f++){
 const m=montages.find(m=>f>=Math.round(m.songStart*60)&&f<Math.round(m.songStart*60)+m.frames);
 if(m){if(!deck)deck=decodeVideo(`public/${m.id}.mp4`,1920,1080);const next=await deck.frames.next();if(next.done)throw Error('Missing source frame');vctx.putImageData(new ImageData(new Uint8ClampedArray(next.value.buffer,next.value.byteOffset,next.value.byteLength),1920,1080),0,0);if(f===Math.round(m.songStart*60)+m.frames-1){if(!(await deck.frames.next()).done)throw Error('Extra source frames');await deck.done;deck=undefined;}}
 drawScene(ctx as unknown as CanvasRenderingContext2D,f/60,format,data,layouts,bands,motion,{art:art as unknown as CanvasImageSource,dropOne:video as unknown as CanvasImageSource,dropTwo:video as unknown as CanvasImageSource,pictureTime:f/60});const rgba=ctx.getImageData(0,0,size,size).data,rgb=Buffer.allocUnsafe(size*size*3);for(let i=0;i<size*size;i++)for(let c=0;c<3;c++)rgb[i*3+c]=rgba[i*4+c]!;expected.push(rgb);
}
const child=spawn('ffmpeg',['-v','error','-threads','2','-i',file,'-an','-vf',`crop=${crop.w}:${crop.h}:${crop.x}:${crop.y}:exact=1,scale=${size}:${size}:flags=area`,'-pix_fmt','rgb24','-fps_mode','passthrough','-f','rawvideo','pipe:1'],{stdio:['ignore','pipe','inherit']}),done=new Promise<void>((resolve,reject)=>child.once('close',code=>code===0?resolve():reject(Error('Decode failed'))));void done.catch(()=>{});
let frames=0,maxMae=0,failed=0;const samples:any[]=[],events:any[]=[],failures:any[]=[];const mae=(a:Buffer,b:Buffer)=>{let sum=0;for(let i=0;i<a.length;i++)sum+=Math.abs(a[i]!-b[i]!);return sum/a.length;};
for await(const buffer of rawFrames(child.stdout,size*size*3)){const error=mae(buffer,expected[frames]!);maxMae=Math.max(maxMae,error);if(error>10){failed++;if(failures.length<30)failures.push({frame:frames,mae:error});}if(frames%600===0)samples.push({frame:frames,mae:error});if(critical.has(frames)){const neighbors=[];for(let shift=-2;shift<=2;shift++)if(expected[frames+shift])neighbors.push({shift,mae:mae(buffer,expected[frames+shift]!)});events.push({frame:frames,events:critical.get(frames),mae:error,neighborComparison:neighbors});}frames++;}
await done;if(frames!==data.frames)throw Error('Incomplete frame inventory');const hash=createHash('sha256');for await(const b of createReadStream(file))hash.update(b);const report={status:failed?'failed':'passed',inputFile:basename(file),inputSha256:hash.digest('hex'),format,frames,sourceRegion:crop,comparisonSize:[size,size],threshold:10,maxMeanAbsoluteChannelError:maxMae,failureCount:failed,failures,samples,criticalEvents:events,method:'Every encoded frame is compared with the approved scene at the same exact frame time in a text-free image region, downsampled to 96×96. Both trailer assets are decoded in full frame order. Detects missing, displaced or mistimed major picture changes; low-resolution similarity does not certify every image pixel. Event neighbors are retained for inspection.'};writeFileSync(`evidence/picture-${format}.json`,JSON.stringify(report,null,2)+'\n');console.log({format,frames,maxMae,failed,events:events.length});if(failed)process.exitCode=1;
