import {execFileSync} from 'node:child_process';import {readFileSync,writeFileSync,mkdirSync,renameSync,existsSync,createReadStream} from 'node:fs';import {basename,join} from 'node:path';import {createHash} from 'node:crypto';
const file=process.argv[2],format=process.argv[3];if(!file||!['landscape','portrait'].includes(format??''))throw Error('Usage: file landscape|portrait');
const run=(args:string[])=>execFileSync('ffmpeg',args,{encoding:'utf8',maxBuffer:4*1024*1024}),hash=async(p:string)=>{const h=createHash('sha256');for await(const b of createReadStream(p))h.update(b);return h.digest('hex');};
const videoHash=(p:string)=>run(['-v','error','-threads','2','-i',p,'-map','0:v:0','-an','-pix_fmt','yuv420p','-f','hash','-hash','sha256','-']).trim().replace(/^SHA256=/,'');
const beforeHash=await hash(file),decodedBefore=videoHash(file);mkdirSync('output/encoding-intermediates',{recursive:true});const old=join('output/encoding-intermediates',basename(file));if(existsSync(old))throw Error('Original intermediate already exists');renameSync(file,old);
run(['-v','error','-i',old,'-map','0','-c','copy','-bsf:v','h264_metadata=sample_aspect_ratio=1/1:video_full_range_flag=0:colour_primaries=1:transfer_characteristics=1:matrix_coefficients=1','-movflags','+faststart',file]);const decodedAfter=videoHash(file);if(decodedBefore!==decodedAfter)throw Error('Decoded pixels changed during metadata finalization');const finalHash=await hash(file);
const report={status:'passed',file:basename(file),format,beforeSha256:beforeHash,sha256:finalHash,decodedVideoSha256:decodedAfter,method:'Lossless stream-copy remux, setting explicit 1:1 H.264 sample-aspect and limited-range Rec.709 metadata. Complete decoded YUV frame bytes match before/after; no picture re-encode.'};writeFileSync(`evidence/container-${format}.json`,JSON.stringify(report,null,2)+'\n');
for(const kind of ['focus','picture','checkpoints']){const path=`evidence/${kind}-${format}.json`;if(existsSync(path)){const proof=JSON.parse(readFileSync(path,'utf8'));if(proof.inputSha256!==beforeHash)throw Error('Unexpected prior proof identity');proof.originalVerifiedSha256=beforeHash;proof.inputSha256=finalHash;proof.identityTransfer=`container-${format}.json proves complete decoded pixels unchanged after metadata-only remux`;writeFileSync(path,JSON.stringify(proof,null,2)+'\n');}}
console.log(report);
