import {useEffect,useState} from 'react';
import {AbsoluteFill,Img,Audio,staticFile,useCurrentFrame,delayRender,continueRender,cancelRender,random} from 'remotion';
import cuesData from './cues.json';
import science from '../public/science.json';
import motion from '../public/motion.json';
export type Word={text:string;start:number;end:number};
export type Cue={id:string;lang:string;text:string;start:number;end:number;words:Word[];translation?:string;translationGroups?:Word[]};
const cues:readonly Cue[]=cuesData;
const clamp=(x:number)=>Math.max(0,Math.min(1,x));
const smooth=(x:number)=>{const a=clamp(x);return a*a*(3-2*a);};
const duration=22763/60,blue='#285fc5',cyan='#007da6',ink='#10366d';
const frameTime=(x:number)=>Math.round(x*60)/60;
function active(lang:string,t:number){const track=cues.filter(c=>c.lang===lang);return track.find(c=>t>=frameTime(c.start)&&t<frameTime(c.end))??track.find(c=>c.start>t&&c.start-t<=.12)??track.find(c=>t>=c.end&&t<c.end+.08);}
const Text=({words,t,color,translated=false}:{words:Word[];t:number;color:string;translated?:boolean})=><>{words.map((w,i)=>{const on=t>=frameTime(w.start)&&t<frameTime(w.end),release=t>=frameTime(w.end)&&t<frameTime(w.end)+1/60;return <span data-word={i} key={i} style={{display:'inline-block',position:'relative',marginRight:translated?8:10,color:on?ink:translated?'#3f607c':'#42617f',textShadow:on?`0 0 14px ${color}20`:'none'}}>{w.text}<span style={{position:'absolute',left:0,right:0,bottom:translated?-3:-4,height:translated?2:3,background:color,opacity:on?1:release?.2:0}}/></span>;})}</>;
const Rail=({c,t,color}:{c:Cue;t:number;color:string})=>{let stage=0;for(let i=0;i<c.words.length;i++){const w=c.words[i]!;if(t>=w.end)stage=i+1;else if(t>=w.start){stage=i+clamp((t-w.start)/(w.end-w.start));break;}else break;}return <div style={{marginTop:25,width:650,height:2,background:`${color}22`}}><div style={{width:650*stage/c.words.length,height:2,background:color,opacity:.75}}/></div>;};
const Lane=({lang,t}:{lang:'fr'|'en';t:number})=>{const c=active(lang,t),fr=lang==='fr',color=fr?blue:cyan;const opacity=c?t<c.start?smooth((t-c.start+.12)/.07):t>c.end?1-smooth((t-c.end)/.08):1:1;return <div style={{position:'absolute',left:76,top:fr?220:594,width:920,height:fr?340:213}}><div style={{display:'flex',alignItems:'center',gap:16,fontSize:12,letterSpacing:4,color}}><span style={{width:44,height:3,background:color}}/>{fr?'ROI / FRANÇAIS':'ADORE / ENGLISH'}</div>{c?<div data-cue={c.id} style={{position:'absolute',top:44,width:920,opacity}}><div style={{fontSize:fr?(c.text.length>65?36:42):(c.text.length>39?45:51),fontWeight:650,lineHeight:1.22,letterSpacing:-.6,textTransform:'uppercase'}}><Text words={c.words} t={t} color={color}/></div>{fr&&<div data-translation style={{marginTop:24,fontFamily:'Playfair',fontSize:31,lineHeight:1.3,fontWeight:500}}><Text words={c.translationGroups??[]} t={t} color={color} translated/></div>}<Rail c={c} t={t} color={color}/></div>:<div style={{marginTop:37,fontFamily:'Playfair',fontSize:fr?43:36,color:'#6389a8'}}>{fr?'Roi':'Did I tell u that I miss u?'}</div>}</div>;};
const Spectrum=({row}:{row:number[]})=><div style={{position:'absolute',left:76,top:870,width:1768,height:165}}><div style={{fontSize:9,letterSpacing:2.5,color:'#4b7492',position:'absolute',left:0,top:-19}}>STEREO · BAND LEVEL · dBFS</div><svg width={1768} height={165} shapeRendering="geometricPrecision">{[-60,-30,0].map(level=>{const y=120-(level+60)/60*108;return <g key={level}><line x1={30} x2={1768} y1={y} y2={y} stroke="#7094b4" strokeOpacity={level===-60?.3:.12}/><text x={0} y={y+3} fill="#6487a5" fontSize={9}>{level}</text></g>;})}{Array.from({length:64},(_,i)=>{const h=clamp(((row[i]??-120)+60)/60)*108,x=40+i*1715/63;return <line data-band={i} key={i} x1={x} x2={x} y1={120} y2={120-h} stroke={i<18?blue:cyan} strokeWidth={8} strokeLinecap="butt"/>;})}{[20,60,250,1000,4000,20000].map((hz,i)=>{const x=40+Math.log(hz/20)/Math.log(1000)*1715;return <g key={hz}><line x1={x} x2={x} y1={126} y2={132} stroke="#608dab"/><text x={x} y={149} fill="#426b8b" fontSize={10} letterSpacing={1.7} textAnchor={i===0?'start':i===5?'end':'middle'}>{['20 Hz','60','250','1k','4k','20k'][i]}</text></g>;})}</svg></div>;
let fontTask:Promise<void>|null=null;
export const ensureFonts=()=>fontTask??=Promise.all([['Space','SpaceGrotesk.ttf'],['Playfair','Playfair.ttf'],['Bebas','BebasNeue.ttf']].map(async([name,file])=>{const f=new FontFace(name??'Space',`url(${staticFile(file??'SpaceGrotesk.ttf')})`,{weight:'100 900'});await f.load();document.fonts.add(f);})).then(()=>undefined);
const Scrims=()=> <AbsoluteFill><AbsoluteFill style={{background:'linear-gradient(90deg,rgba(242,250,255,.98) 0%,rgba(230,246,255,.97) 34%,rgba(226,244,255,.90) 46%,rgba(223,244,255,.35) 60%,transparent 72%)'}}/><div style={{position:'absolute',left:0,right:0,bottom:0,height:265,background:'linear-gradient(0deg,rgba(238,249,255,.98) 0%,rgba(231,246,255,.97) 64%,rgba(231,246,255,.84) 81%,transparent 100%)'}}/></AbsoluteFill>;
export const Film=({sampleTime,externalArtwork=false,layer='all'}:{sampleTime?:number;externalArtwork?:boolean;layer?:'all'|'static'|'dynamic'})=>{
 const frame=useCurrentFrame(),t=sampleTime??frame/60;
 const [handle]=useState(()=>delayRender('Bundled fonts'));useEffect(()=>{ensureFonts().then(()=>continueRender(handle)).catch(cancelRender);},[handle]);
 const f=Math.max(0,Math.min(Math.round(t*60),science.length-1)),row=science[f]??[],m=motion[f]??[],pressure=m[0]??0,impact=m[1]??0,brightness=m[3]??0,width=m[5]??680,thickness=m[6]??2;
 const fade=layer==='all'?smooth(t/1.2)*(1-smooth((t-duration+2.5)/2.5)):1;
 const prev=Math.max(0,...cues.filter(c=>c.end<t).map(c=>c.end)),next=Math.min(duration,...cues.filter(c=>c.start>t).map(c=>c.start));
 const title=t<7.6||t>367||(!cues.some(c=>t>=c.start-.12&&t<c.end+.08)&&next-prev>8&&t>prev+.8&&t<next-1.2);
 if(layer==='static')return <Scrims/>;
 return <AbsoluteFill style={{fontFamily:'Space',fontSynthesis:'none',color:ink}}><Audio src={staticFile('soundtrack.m4a')}/>{!externalArtwork&&<><Img src={staticFile('poster.jpg')} style={{position:'absolute',width:1920,height:1920,top:-300,filter:'blur(12px)'}}/><Img src={staticFile('poster.jpg')} style={{position:'absolute',left:840,top:0,width:1080,height:1080}}/></>}
 <AbsoluteFill style={{opacity:fade}}>{layer!=='dynamic'&&<Scrims/>}
 <div style={{position:'absolute',inset:28,border:'1px solid #9ed4f34d'}}/>{[[28,28],[1862,28],[28,1022],[1862,1022]].map(([x,y],i)=><div key={i} style={{position:'absolute',left:x,top:y,width:28,height:28,borderTop:i<2?'3px solid #76c9ff':undefined,borderBottom:i>=2?'3px solid #3695c9':undefined,borderLeft:i%2===0?'3px solid #3695c9':undefined,borderRight:i%2?'3px solid #76c9ff':undefined}}/>)}
 <div style={{position:'absolute',left:76,right:76,top:55,display:'flex',justifyContent:'space-between',fontSize:12,letterSpacing:4,color:'#2e618e'}}><span>VIDEOCLUB <span style={{color:blue}}> / </span> ADORE</span><span style={{fontSize:10,color:'#e6f7ff',textShadow:'0 1px 8px #153c75'}}>ROI × DID I TELL U THAT I MISS U</span></div>
 <svg width={1920} height={60} style={{position:'absolute',top:115}}><defs><filter id="glow"><feGaussianBlur stdDeviation={5+impact*8}/></filter></defs><g filter="url(#glow)" opacity={.12+impact*.4}><line x1={960-width/2} x2={944} y1={30} y2={30} stroke="#148bf7" strokeWidth={thickness+5}/><line x1={976} x2={960+width/2} y1={30} y2={30} stroke="#b4efff" strokeWidth={thickness+5}/></g><line x1={960-width/2} x2={944} y1={30} y2={30} stroke={blue} strokeWidth={thickness}/><line x1={976} x2={960+width/2} y1={30} y2={30} stroke="#92e0ff" strokeWidth={thickness}/><path d="M960 25L965 30L960 35L955 30Z" fill="#47aae0"/></svg>
 {Array.from({length:24},(_,i)=>{const x=random(`x${i}`)*1920,y=(random(`y${i}`)*1300-t*(2+random(`v${i}`)*6)+13000)%1300-100;return <div key={i} style={{position:'absolute',left:x,top:y,width:i%7===0?3:2,height:i%7===0?3:2,background:x>1050?'#c9f1ff':'#498ed0',opacity:.10+brightness*.12+pressure*.05}}/>;})}
 {title?<div style={{position:'absolute',left:76,top:286,width:900}}><div style={{fontSize:13,letterSpacing:5,color:cyan,marginBottom:19}}>{t<8?'TWO VOICES / ONE MOMENT':t>367?'STILL IN THE MOMENT':'THE SPACE BETWEEN'}</div><div style={{fontFamily:'Bebas',fontSize:154,lineHeight:1,letterSpacing:2}}>ROI</div><div style={{fontFamily:'Playfair',fontSize:57,lineHeight:1.18,color:'#356697',marginTop:18}}>Did I tell u<br/>that I miss u?</div></div>:<><Lane lang="fr" t={t}/><div style={{position:'absolute',left:76,top:565,width:840,height:1,background:'linear-gradient(90deg,#2c70bf55,transparent)'}}/><Lane lang="en" t={t}/></>}
 <Spectrum row={row}/><div style={{position:'absolute',left:76,bottom:32,fontSize:9,letterSpacing:3,color:'#6388a5'}}>IN THE MOMENT</div><div style={{position:'absolute',right:76,bottom:32,fontSize:10,letterSpacing:3,color:'#426f91'}}>{String(Math.floor(t/60)).padStart(2,'0')}:{String(Math.floor(t%60)).padStart(2,'0')}</div></AbsoluteFill></AbsoluteFill>;
};
