import {readFileSync,writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {parseData} from '../src/schema.ts';
const read=(p:string)=>JSON.parse(readFileSync(p,'utf8'));
const write=(p:string,v:unknown)=>writeFileSync(p,JSON.stringify(v,null,2)+'\n');
const hash=(b:string|Uint8Array)=>createHash('sha256').update(b).digest('hex');
const data=parseData(read('src/cues.json')),identity=read('evidence/preview-identity.json');
const prior=read('evidence/sync-review.json');if(prior.actualAudioReviewComplete||prior.authorization?.approved)throw Error('Preserve completed review evidence; archive it before regenerating a new revision.');
const ledger=read('analysis/boundary-ledger.json') as {id:string;selected:unknown;candidates:{method:string;word:string;start:number;end:number}[];[k:string]:unknown}[];
for(const cue of data.cues)for(const word of cue.ru){
 let row=ledger.find(w=>w.id===word.id);if(!row){row={id:word.id,selected:{},candidates:[{method:'bounded MMS vocalisation',word:word.text,start:word.startSample/data.sampleRate,end:word.endSample/data.sampleRate}]};ledger.push(row);}
 row.selected={startSample:word.startSample,endSample:word.endSample};row.selectedMethod='Section MMS onset/core, inspected vocal-energy release refinement where documented; preview candidate';row.candidateSpreadMs=word.candidateSpreadMs;row.listeningReview='incomplete';row.waveformSpectrogramReview=read('analysis/release-candidates.json').observations.some((o:{id:string})=>o.id===word.id)?'release contact sheet inspected':'candidate inspector available; no manual acoustic certification';
}
write('analysis/boundary-ledger.json',ledger);
write('evidence/timing-status.json',{status:'preview candidates; actual-audio review incomplete',sourceEvents:data.cues.reduce((n,c)=>n+c.ru.length,0),lexicalSourceWords:220,nonlexicalEvents:1,targetTokens:306,cues:data.cues.length,above25ms:data.cues.flatMap(c=>c.ru).filter(w=>w.candidateSpreadMs>25).length,sampleRate:data.sampleRate,sampleCount:data.sampleCount,frames:data.frames,releaseExtensions:read('analysis/release-candidates.json').observations.length,uncertainty:'Candidate disagreement and spectral evidence are retained; frame quantization is not a measurement of acoustic accuracy.'});
const media=['public/review-source.mp4','public/soundtrack.m4a'];
const packetHashes=media.map(p=>execFileSync('ffmpeg',['-v','error','-i',p,'-map','0:a:0','-c','copy','-f','hash','-hash','sha256','-'],{encoding:'utf8'}).trim());
const pcmHashes=media.map(p=>execFileSync('ffmpeg',['-v','error','-i',p,'-map','0:a:0','-c:a','pcm_f32le','-f','hash','-hash','sha256','-'],{encoding:'utf8'}).trim());
if(packetHashes[0]!==packetHashes[1]||pcmHashes[0]!==pcmHashes[1])throw Error('Source/preview audio mismatch');
const audio=read('source/audio-probe.json');
write('source/input-manifest.json',{sourceUrl:'https://www.youtube.com/watch?v=3yDdoi1c7-8',sourceId:'3yDdoi1c7-8',title:'каждый, кто делал тебе больно',artist:'забей, лерочка',provider:'Spooky music',sourceMetadata:{descriptionReleaseDate:'2021-07-09',descriptionPhonogram:'2023 Spooky music',note:'The supplied auto-generated upload contains both dates; neither is silently reconciled.'},artwork:{type:'Static ink illustration extracted from original upload at 15 seconds',illustrator:'Not identified in verified upload metadata',transform:'Code-authored tritone treatment and motion; not original source animation'},sourceFiles:Object.fromEntries(media.concat('public/artwork.png').map(p=>[p,{bytes:readFileSync(p).length,sha256:hash(readFileSync(p))}])),audio:{codec:'AAC LC',sampleRate:44100,channels:2,containerDuration:audio.format.duration,decodedSamples:data.sampleCount,decodedDuration:data.duration,originalPacketHash:packetHashes[0],previewPacketHash:packetHashes[1],originalFloatPcmHash:pcmHashes[0],previewFloatPcmHash:pcmHashes[1],status:'Bit-identical encoded audio payload and decoded PCM; no retiming or gain change',clockNote:'Decoded AAC tail padding yields 213.285442 seconds; media element reports approximately 213.273 seconds. Preview follows media currentTime; 60 fps coverage uses ceil, never truncates the recording.'},tools:{node:process.versions.node,ffmpeg:execFileSync('ffmpeg',['-version'],{encoding:'utf8'}).split('\n')[0],remotion:'4.0.518',alignment:'MMS_FA + stable-whisper large-v3-turbo; Whisper small independent free recognition; Demucs htdemucs analysis stem'}});
write('evidence/sync-review.json',{song:identity.song,revision:identity.revision,inputHashes:identity.hashes,status:'preview-review-pending',actualAudioReviewComplete:false,translationReviewComplete:true,allCuesAllFormatsComplete:false,reviewerRole:'AI-assisted lexical, semantic, signal and visual inspection; no completed listening attestation',actualAudioMethod:'Incomplete. Playback smoke checks are not complete actual-audio review.',unresolvedDefects:[],reviewQuestions:['32 release candidates, especially two manually shortened tails at 83.920 and 153.860 seconds','Nonlexical У-у-у / Ooh candidate at 154.415–155.962 seconds','Brief connecting words and all model spreads exceeding 25 ms; repeated hooks require independent listening'],cues:data.cues.map(c=>({id:c.id,meaning:true,normalAudio:false,slowAudio:false,landscape:false,portrait:false})),authorization:{approved:false,revision:null,evidence:null},deliveryAcceptance:'pending current revision',publicationStatus:'source preview only; full media not published',note:'Technical checks and positive direction feedback do not authorize production rendering.'});
console.log('Updated candidate ledger, preserved source audio, frozen review scope.');
