import previewIdentity from '../evidence/preview-identity.json';
import raw from './cues.json';
import layouts from './layout.json';
import bands from '../public/science.json';
import acoustic from '../public/acoustic.json';
import ledger from '../analysis/boundary-ledger.json';
import {parseData,object,array} from './schema.ts';
import type {Format,SourceWord} from './schema.ts';
import {sceneSvg} from './scene.ts';
import {activeSource} from './focus.ts';
const data=parseData(raw);
const element=<T extends HTMLElement>(id:string):T=>{const e=document.getElementById(id);if(!e)throw Error('Missing '+id);return e as T;};
const video=element<HTMLVideoElement>('video'),stage=element('stage'),overlay=element('overlay'),seek=element<HTMLInputElement>('seek');
const playbackStatus=element('playback-status'),retryPlayback=element<HTMLButtonElement>('retry-playback');
let waitingTimer:ReturnType<typeof setTimeout>|undefined;
function playbackMessage(message:string,retry=false){playbackStatus.textContent=message;retryPlayback.hidden=!retry;}
function ready(){clearTimeout(waitingTimer);playbackMessage('');}
function unavailable(){clearTimeout(waitingTimer);playbackMessage('Recording unavailable. If the local preview server stopped, run Start Preview.command from the preview folder, then retry. Your review notes stay here.',true);}
async function playRecording(){try{await video.play();}catch(error){if(error instanceof DOMException&&error.name==='AbortError')return;unavailable();}}
function reloadRecording(){const position=video.currentTime;loopEnd=undefined;playbackMessage('Reconnecting to the recording…');video.addEventListener('loadedmetadata',()=>{video.currentTime=Math.min(position,video.duration);void playRecording();},{once:true});video.load();}
retryPlayback.onclick=reloadRecording;
video.addEventListener('error',unavailable);
if(video.error)unavailable();
video.addEventListener('playing',ready);
video.addEventListener('canplay',ready);
video.addEventListener('waiting',()=>{clearTimeout(waitingTimer);playbackMessage('Buffering recording…');waitingTimer=setTimeout(async()=>{try{const response=await fetch('/public/review-source.mp4',{method:'HEAD',cache:'no-store',signal:AbortSignal.timeout(4000)});if(!response.ok)throw Error('Media unavailable');if(video.readyState<3)playbackMessage('Playback is taking longer than expected. Retry to reconnect at this position.',true);}catch{unavailable();}},4000);});
let format:Format='landscape',cueIndex=0,selectedWord=0,lastFrame=-1,loopEnd:number|undefined;
const storageKey='kazhdyy-review-'+previewIdentity.revision;
const saveDraft=()=>{const row=records[cueIndex];if(row)row.notes=element<HTMLTextAreaElement>('notes').value;localStorage.setItem(storageKey,JSON.stringify({identity:previewIdentity.hashes,records,edits}));};
const records=data.cues.map(c=>({id:c.id,landscape:false,portrait:false,normalAudio:false,slowAudio:false,notes:''}));
const edits:Record<string,{startSample:number;endSample:number}>={};
const getCue=()=>{const cue=data.cues[cueIndex];if(!cue)throw Error('Cue missing');return cue;};
const time=(t:number)=>{const ms=Math.round(t*1000);return `${Math.floor(ms/60000)}:${String(Math.floor(ms/1000)%60).padStart(2,'0')}.${String(ms%1000).padStart(3,'0')}`;};
function resize(){const box=element('stage-wrap'),l=layouts[format],scale=Math.min(box.clientWidth/l.width,box.clientHeight/l.height);stage.style.width=l.width*scale+'px';stage.style.height=l.height*scale+'px';video.style.top=format==='portrait'?(265/1920*100)+'%':'0';video.style.height=format==='portrait'?(650/1920*100)+'%':'100%';video.style.maskImage=format==='portrait'?'linear-gradient(transparent,black 12%,black 82%,transparent)':'none';lastFrame=-1;}
function list(){element('cue-list').replaceChildren(...data.cues.map((c,i)=>{const b=document.createElement('button');b.className='cue-item'+(i===cueIndex?' active':'');const r=records[i];b.textContent=`${c.id} · ${time(c.startSample/data.sampleRate)} ${r?.landscape?'16:9 ✓':''} ${r?.portrait?'9:16 ✓':''}`;const s=document.createElement('span');s.textContent=c.ru.map(w=>w.text).join(' ');b.append(s);b.onclick=()=>selectCue(i);return b;}));}
function drawAudio(word:SourceWord){const canvas=element<HTMLCanvasElement>('acoustic'),ctx=canvas.getContext('2d');if(!ctx)return;const start=Math.max(0,word.startSample/data.sampleRate-.75),end=word.endSample/data.sampleRate+.75,w=canvas.width,h=canvas.height,step=acoustic.hop/acoustic.sampleRate;ctx.fillStyle='#080e18';ctx.fillRect(0,0,w,h);for(let x=0;x<w;x++){const t=start+(end-start)*x/w,j=Math.floor(t/step),wv=acoustic.wave[j]??[0,0],s=acoustic.spec[j]??[];ctx.strokeStyle='#c6dbea';ctx.beginPath();ctx.moveTo(x,65-(wv[0]??0)*190);ctx.lineTo(x,65-(wv[1]??0)*190);ctx.stroke();for(let b=0;b<80;b++){const v=(s[b]??0)/255;ctx.fillStyle=`rgb(${Math.round(235*v)},${Math.round(180*v)},${Math.round(50+100*v)})`;ctx.fillRect(x,275-b*1.9,1,2);}}
for(const [i,s] of [word.startSample,word.endSample].entries()){const x=(s/data.sampleRate-start)/(end-start)*w;ctx.strokeStyle=i===0?'#66ead0':'#ffad8b';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke();}ctx.fillStyle='#fff';ctx.font='17px system-ui';ctx.fillText(time(start),8,22);ctx.fillText(time(end),w-115,22);}
function inspect(index:number){selectedWord=index;const cue=getCue(),word=cue.ru[index];if(!word)return;drawAudio(word);const holder=element('inspector');holder.replaceChildren();const title=document.createElement('strong');title.textContent=word.text+" → "+cue.en.filter(t=>t.sourceIds.includes(word.id)).map(t=>t.text).join(" " );holder.append(title);const row=document.createElement('div');row.className='row';const start=document.createElement('input'),end=document.createElement('input');for(const input of [start,end]){input.type='number';input.step='.005';}start.value=(word.startSample/data.sampleRate).toFixed(3);end.value=(word.endSample/data.sampleRate).toFixed(3);start.setAttribute('aria-label','Proposed onset');end.setAttribute('aria-label','Proposed exclusive end');const apply=document.createElement('button');apply.textContent='Propose boundary edit';apply.onclick=()=>{const a=Number(start.value),b=Number(end.value);if(!Number.isFinite(a)||!Number.isFinite(b)||a<0||b<=a||b>data.duration)return;word.startSample=Math.round(a*data.sampleRate);word.endSample=Math.round(b*data.sampleRate);cue.startSample=Math.min(...cue.ru.map(w=>w.startSample));cue.endSample=Math.max(...cue.ru.map(w=>w.endSample));cue.visibleFrom=Math.max(0,cue.startSample-Math.round(.24*data.sampleRate));cue.visibleUntil=Math.min(data.sampleCount,cue.endSample+Math.round(.28*data.sampleRate));edits[word.id]={startSample:word.startSample,endSample:word.endSample};const r=records[cueIndex];if(r){r.landscape=false;r.portrait=false;r.normalAudio=false;r.slowAudio=false;}lastFrame=-1;inspect(index);status();saveDraft();};const play=document.createElement('button');play.textContent='Listen around this word';play.onclick=()=>{video.currentTime=Math.max(0,word.startSample/data.sampleRate-.6);loopEnd=word.endSample/data.sampleRate+.6;void playRecording();};row.append('Onset',start,'End',end,apply,play);holder.append(row);const evidence=ledger.find(w=>w.id===word.id),p=document.createElement('p');p.className='small muted';p.textContent=evidence?.candidates.map(v=>`${v.method}: ${v.start.toFixed(3)}–${v.end.toFixed(3)}`).join(' · ')??'No candidates';holder.append(p);}
function selectCue(i:number,seekTo=true){const old=records[cueIndex];if(old)old.notes=element<HTMLTextAreaElement>('notes').value;cueIndex=Math.max(0,Math.min(data.cues.length-1,i));const c=getCue();if(seekTo){video.currentTime=Math.max(0,c.startSample/data.sampleRate-.4);loopEnd=undefined;}element('cue-title').textContent=c.id+' · '+c.ru.map(w=>w.text).join(' ');element('word-list').replaceChildren(...c.ru.map((word,i)=>{const b=document.createElement('button');b.textContent=word.text;b.dataset.id=word.id;b.onclick=()=>inspect(i);return b;}));element<HTMLTextAreaElement>('notes').value=records[cueIndex]?.notes??'';element<HTMLInputElement>('listen-check').checked=false;inspect(0);list();status();}
function status(){const r=records[cueIndex];element('review-status').textContent=`Current cue: 16:9 ${r?.landscape?'reviewed':'pending'} · 9:16 ${r?.portrait?'reviewed':'pending'} · Slow audio ${r?.slowAudio?'reviewed':'pending'}. ${Object.keys(edits).length} proposed word edits.`;}
element('play').onclick=()=>{loopEnd=undefined;if(video.paused){if(video.error)reloadRecording();else void playRecording();}else video.pause();};video.onplay=()=>{element('play').textContent='Pause';};video.onpause=()=>{element('play').textContent=video.ended?'Replay recording':'Play recording';};
element('restart').onclick=()=>{loopEnd=undefined;video.currentTime=0;selectCue(0,false);void playRecording();};
element('toggle-tools').onclick=()=>{const watch=document.body.classList.toggle('watch');element('toggle-tools').textContent=watch?'Timing review':'Watch preview';resize();};
element('previous').onclick=()=>selectCue(cueIndex-1);element('next').onclick=()=>selectCue(cueIndex+1);
element<HTMLSelectElement>('speed').onchange=e=>{if(e.target instanceof HTMLSelectElement)video.playbackRate=Number(e.target.value);};seek.oninput=()=>{video.currentTime=Number(seek.value);loopEnd=undefined;const index=data.cues.findIndex(c=>video.currentTime>=c.visibleFrom/data.sampleRate&&video.currentTime<c.visibleUntil/data.sampleRate);if(index>=0)selectCue(index,false);};seek.max=String(data.duration);
for(const f of ['landscape','portrait'] as const)element(f).onclick=()=>{format=f;for(const k of ['landscape','portrait'])element(k).classList.toggle('selected',k===f);element<HTMLInputElement>('listen-check').checked=false;resize();status();};
element('mark-review').onclick=()=>{if(!element<HTMLInputElement>('listen-check').checked)return;const r=records[cueIndex];if(!r)return;r[format]=true;if(video.playbackRate===1)r.normalAudio=true;else r.slowAudio=true;r.notes=element<HTMLTextAreaElement>('notes').value;element<HTMLInputElement>('listen-check').checked=false;status();list();saveDraft();};
element<HTMLTextAreaElement>('notes').oninput=saveDraft;
element('save-review').onclick=async()=>{saveDraft();const r=records[cueIndex];if(r)r.notes=element<HTMLTextAreaElement>('notes').value;const payload={status:'listener progress — does not approve production',savedAt:new Date().toISOString(),previewRevision:previewIdentity.revision,inputHashes:previewIdentity.hashes,audioSha256:data.audioSha256,cues:records,proposedTimingEdits:edits};try{const response=await fetch('/api/review-progress',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});element('save-status').textContent=response.ok?'Review progress saved. Corrections and remaining full-track checks must be resolved before production.':'Could not save review progress. Your local draft is preserved.';}catch{element('save-status').textContent='Preview server unavailable. Your local draft is preserved; restart the preview and save again.';}};
const expand=()=>{const box=element("stage-wrap"),expanded=box.classList.toggle("expanded");element("close-expanded").hidden=!expanded;document.body.style.overflow=expanded?"hidden":"";resize();};element("fullscreen").onclick=expand;element("close-expanded").onclick=expand;document.addEventListener("keydown",event=>{if(event.key==="Escape"&&element("stage-wrap").classList.contains("expanded"))expand();});

try{const saved=localStorage.getItem(storageKey);if(saved){const value:unknown=JSON.parse(saved);const d=object(value);if(JSON.stringify(d.identity)!==JSON.stringify(previewIdentity.hashes)){localStorage.setItem(storageKey+'-archived-'+Date.now(),saved);element('save-status').textContent='Earlier review notes are preserved in an archived local draft. This updated preview needs a fresh review record.';}else{const old=array(d.records).map(object);for(const r of records){const prior=old.find(v=>v.id===r.id);if(prior){for(const key of ['landscape','portrait','normalAudio','slowAudio'] as const)r[key]=prior[key]===true;r.notes=typeof prior.notes==='string'?prior.notes:'';}}const proposals=object(d.edits);for(const c of data.cues){for(const w of c.ru){const p=proposals[w.id];if(p){const e=object(p),a=Number(e.startSample),b=Number(e.endSample);if(Number.isSafeInteger(a)&&Number.isSafeInteger(b)&&a>=0&&b>a&&b<=data.sampleCount){w.startSample=a;w.endSample=b;edits[w.id]={startSample:a,endSample:b};}}}c.startSample=Math.min(...c.ru.map(w=>w.startSample));c.endSample=Math.max(...c.ru.map(w=>w.endSample));}}}}catch{element('save-status').textContent='Saved local draft could not be restored; frozen preview remains available.';}

await Promise.all([document.fonts.load('500 78px LyricSans'),document.fonts.load('700 116px LyricSans')]);
let measuredFrames=0,renderTotalMs=0,renderMaxMs=0;const recentPaintMs:number[]=[];
function tick(){const frame=Math.min(data.frames-1,Math.round(video.currentTime*data.fps));if(frame!==lastFrame){const liveIndex=data.cues.findIndex(c=>video.currentTime>=c.startSample/data.sampleRate&&video.currentTime<c.endSample/data.sampleRate);const selected=getCue(),selectedVisible=video.currentTime>=selected.visibleFrom/data.sampleRate&&video.currentTime<selected.visibleUntil/data.sampleRate;if(liveIndex>=0&&liveIndex!==cueIndex&&!selectedVisible&&!video.paused)selectCue(liveIndex,false);const paintStart=performance.now();overlay.innerHTML=sceneSvg(frame,format,data,layouts,bands);overlay.dataset.frame=String(frame);if(!video.paused){const ms=performance.now()-paintStart;measuredFrames++;renderTotalMs+=ms;renderMaxMs=Math.max(renderMaxMs,ms);recentPaintMs.push(ms);if(recentPaintMs.length>600)recentPaintMs.shift();if(measuredFrames%60===0){const sorted=[...recentPaintMs].sort((a,b)=>a-b);overlay.dataset.paintDiagnostics=JSON.stringify({frames:measuredFrames,meanMs:renderTotalMs/measuredFrames,maxMs:renderMaxMs,recentP95Ms:sorted[Math.floor(sorted.length*.95)],scope:'SVG construction and DOM assignment only; excludes compositor, display and hardware audio latency'});}}element('time').textContent=time(video.currentTime);seek.value=String(video.currentTime);const c=getCue(),active=activeSource(c,frame,data);for(const b of element('word-list').querySelectorAll('button')){b.classList.toggle('active',active.has(b.dataset.id??''));b.classList.toggle('focus',b.dataset.id===c.ru[selectedWord]?.id);}lastFrame=frame;}if(loopEnd!==undefined&&video.currentTime>=loopEnd){video.pause();loopEnd=undefined;}requestAnimationFrame(tick);}
new ResizeObserver(resize).observe(element('stage-wrap'));selectCue(0,false);const params=new URLSearchParams(location.search);if(params.get('format')==='portrait'){format='portrait';element('portrait').classList.add('selected');element('landscape').classList.remove('selected');}const requested=Number(params.get('t')??0);const seekRequested=()=>{video.currentTime=Math.max(0,Math.min(data.duration-.1,requested));const index=data.cues.findIndex(c=>video.currentTime>=c.visibleFrom/data.sampleRate&&video.currentTime<c.visibleUntil/data.sampleRate);if(index>=0)selectCue(index,false);};if(video.readyState>=1)seekRequested();else video.addEventListener('loadedmetadata',seekRequested,{once:true});if(params.get('clean')==='1')document.body.classList.add('clean');resize();tick();
