"""Generate src/shots.ts from measured cut candidates plus reviewed overrides.

Every portrait centre, fit decision, lyric zone and lettering protection below
was chosen by inspecting the labelled segment and portrait-crop sheets
(analysis/shot_sheets.py, analysis/portrait_sheets.py). Segment indices refer
to analysis/work/segments.json (histogram/luma cut candidates).
"""
import csv
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
HALF = 1080 * 9 / 16 / 1920 / 2  # half portrait crop width, normalized

# Reviewed portrait framing. Number = crop centre; (a, b) = linear pan across
# the shot; "fit" = whole 16:9 frame over a dimmed source fill (authored text).
PORTRAIT = {
    13: "fit", 14: "fit", 16: "fit", 17: "fit", 18: "fit",
    20: 0.58, 36: "fit", 44: 0.62, 45: 0.60, 46: (0.63, 0.45),
    52: "fit", 53: "fit", 57: 0.62, 60: "fit", 63: 0.58, 66: "fit", 69: "fit",
    71: "fit", 72: "fit", 73: "fit", 82: 0.40, 83: "fit", 86: "fit",
    115: 0.64, 116: 0.64, 117: 0.64, 118: "fit", 119: "fit", 120: "fit", 128: "fit",
    141: "fit", 142: "fit", 143: "fit", 144: "fit", 145: "fit", 146: "fit", 147: "fit", 148: "fit", 149: "fit",
}
# Authored source lettering, UI and logos: no source-light response on them.
PROTECT = {0, 1, 2, 13, 14, 16, 17, 18, 36, 52, 53, 57, 60, 66, 69, 71, 72, 73, 83, 86, 88, 89, 105, 118, 119, 120, 128,
           141, 142, 143, 144, 145, 146, 147, 148, 149}
# Landscape lyric zone overrides: dialogue boxes and UI in the lower frame.
ZONE = {35: "upper", 36: "upper", 57: "upper", 83: "upper", 86: "upper", 118: "bottom", 119: "bottom", 120: "bottom", 128: "bottom"}


def main() -> None:
    segs = json.loads((ROOT / "analysis" / "work" / "segments.json").read_text(encoding="utf-8"))
    rows = list(csv.DictReader(open(ROOT / "analysis" / "work" / "frame-metrics.csv", encoding="utf-8")))
    shots = []
    for s in segs:
        k, a, b = s["segment"], s["startFrame"], s["endFrame"]
        xs = [float(r["edgeCentreX"]) for r in rows[a:b]]
        p = PORTRAIT.get(k, sum(xs) / len(xs))
        clamp = lambda v: round(min(1 - HALF, max(HALF, v)), 3)  # noqa: E731
        if p == "fit":
            portrait = {"mode": "fit"}
        elif isinstance(p, tuple):
            portrait = {"mode": "crop", "x": clamp(p[0]), "x2": clamp(p[1])}
        else:
            portrait = {"mode": "crop", "x": clamp(p)}
        shots.append({"segment": k, "startFrame": a, "endFrame": b, "portrait": portrait,
                      "zone": ZONE.get(k, "lower"), "protect": k in PROTECT})
    # Short in-between segments (flash frames, dissolve centres) become
    # transitions: the portrait centre glides between neighbours instead of
    # jumping twice.
    for i in range(1, len(shots) - 1):
        s = shots[i]
        if s["endFrame"] - s["startFrame"] < 10 and s["portrait"]["mode"] == "crop" and not s["protect"]:
            prev, nxt = shots[i - 1]["portrait"], shots[i + 1]["portrait"]
            if prev["mode"] == "crop" and nxt["mode"] == "crop":
                s["portrait"] = {"mode": "crop", "x": prev.get("x2", prev["x"]), "x2": nxt["x"]}
    # Merge neighbours whose framing and treatment match (no visible change).
    merged = []
    for s in shots:
        last = merged[-1] if merged else None
        if (last and last["zone"] == s["zone"] and last["protect"] == s["protect"] and last["portrait"]["mode"] == s["portrait"]["mode"]
                and (s["portrait"]["mode"] == "fit" or ("x2" not in last["portrait"] and "x2" not in s["portrait"]
                                                        and abs(last["portrait"]["x"] - s["portrait"]["x"]) < 0.035))):
            last["endFrame"] = s["endFrame"]
            last["segments"].append(s["segment"])
            continue
        merged.append({**s, "segments": [s["segment"]]})
    spf = 1001 / 24000
    lines = [
        "// Generated by analysis/build_shots.py from reviewed segment overrides. Do not hand-edit;",
        "// change the override tables there and regenerate. Times are source seconds (frame × 1001/24000).",
        "export type PortraitFrame = {mode: 'crop'; x: number; x2?: number} | {mode: 'fit'};",
        "export type Shot = {id: string; start: number; end: number; frames: [number, number]; portrait: PortraitFrame; zone: 'lower' | 'bottom' | 'upper'; protect: boolean};",
        "export const SHOTS: readonly Shot[] = [",
    ]
    for i, s in enumerate(merged):
        p = s["portrait"]
        pj = "{mode: 'fit'}" if p["mode"] == "fit" else ("{mode: 'crop', x: %s, x2: %s}" % (p["x"], p["x2"]) if "x2" in p else "{mode: 'crop', x: %s}" % p["x"])
        lines.append(f"  {{id: 'S{i + 1:03d}', start: {s['startFrame'] * spf:.6f}, end: {s['endFrame'] * spf:.6f}, frames: [{s['startFrame']}, {s['endFrame']}], "
                     f"portrait: {pj}, zone: '{s['zone']}', protect: {str(s['protect']).lower()}}}, // segments {','.join(map(str, s['segments']))}")
    lines.append("];")
    (ROOT / "src" / "shots.ts").write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    (ROOT / "analysis" / "shot-map.json").write_text(json.dumps({
        "schema": "lyric-film/shot-map/v1", "method": "Histogram change > 0.30 or mean-luma change > 0.07 between frames (192×108), detections within 3 frames merged; reviewed overrides in analysis/build_shots.py.",
        "candidateSegments": len(segs), "shots": len(merged),
        "fitShots": sum(1 for s in merged if s["portrait"]["mode"] == "fit"), "protectedShots": sum(1 for s in merged if s["protect"]),
    }, indent=2) + "\n", encoding="utf-8", newline="\n")
    print(len(segs), "segments ->", len(merged), "shots")


if __name__ == "__main__":
    main()
