import test from 'node:test';
import assert from 'node:assert/strict';
import {readingWindow,sourceActive,targetActive,visibleCue,type Word,type Target,type Cue,type Timeline} from '../src/model.ts';
import {cueOpacity} from '../src/scene.ts';
import {enforceProductionGate,type Identity,type Review,type Approval} from '../scripts/render-gate.ts';
const words:Word[]=[0,1,2].map(i=>({id:`w${i}`,text:`w${i}`,sourceIndex:i,startSample:44100*(1+i),endSample:44100*(1.4+i),confidence:1,method:'synthetic-boundary-contract'}));
const group:Target={id:'group',text:'union',sourceIndices:[0,2],focusSourceIndices:[0,2],relation:'test',rationale:'Separated test events must not become a broad span'};
test('focus never starts early and releases at the exclusive end',()=>{
  assert.equal(sourceActive(words[0]!,1-1/44100),false);assert.equal(sourceActive(words[0]!,1),true);assert.equal(sourceActive(words[0]!,1.4),false);
});
test('semantic union releases through both gaps and unrelated performed words',()=>{
  for(const t of [1,1.3,3,3.3])assert.equal(targetActive(group,words,t),true);
  for(const t of [.99,1.4,1.8,2,2.2,2.8,3.4])assert.equal(targetActive(group,words,t),false);
});
test('a sustained release beside the next cue cannot steal its entrance or fade either active word',()=>{
  for(const gap of [0,.025,.05,.24]) {
    const end=102.675,nextStart=end+gap;
    const a={start:99,end,...readingWindow(99,end,260,undefined,nextStart)} as Cue;
    const b={start:nextStart,end:104,...readingWindow(nextStart,104,260,a.visibleEnd)} as Cue;
    assert(a.visibleEnd>=a.end);assert(b.visibleStart<=b.start);
    assert(a.visibleEnd<=b.visibleStart);
    assert.equal(cueOpacity(a,end-1/44100),1);
    assert.equal(cueOpacity(b,nextStart+1/44100),1);
  }
});
test('close held-line handoffs have no empty or dim frame before the next vocal',()=>{
  // Independent observed v3 blank frames, not values generated by the new rule.
  for(const [end,nextStart,blank] of [[57.730,57.884989,57.800],[131.504989,131.705011,131.600],[179.664989,179.705011,179.680],[186.764989,187.064989,186.920],[193.260,193.375011,193.320]]) {
    const a={id:'outgoing',start:end!-5,end:end!,...readingWindow(end!-5,end!,260,undefined,nextStart!,end!+.18)} as Cue;
    const b={id:'incoming',start:nextStart!,end:nextStart!+5,...readingWindow(nextStart!,nextStart!+5,260,a.visibleEnd,undefined,nextStart!+5.18)} as Cue;
    const t={cues:[a,b]} as Timeline;
    assert.equal(visibleCue(t,blank!)?.id,'outgoing');assert.equal(cueOpacity(a,blank!),1);
    assert.equal(visibleCue(t,nextStart!-1/44100)?.id,'outgoing');
    assert.equal(visibleCue(t,nextStart!)?.id,'incoming');assert.equal(cueOpacity(b,nextStart!),1);
    assert.equal(a.visibleEnd,b.visibleStart);
  }
});
test('audible-tail reading hold stays full after lexical focus ends, then fades gently',()=>{
  const cue={start:1,end:3,...readingWindow(1,3,20,undefined,10,4.2)} as Cue;
  const word={...words[0]!,startSample:44100,endSample:3*44100};
  for(const time of [3,3.4,4.1,4.2]) {
    assert.equal(sourceActive(word,time),false);assert.equal(cueOpacity(cue,time),1);
  }
  assert.equal(cue.exitMode,'fade');assert.equal(cue.visibleEnd-cue.fullOpacityEnd,.5);
  assert(cueOpacity(cue,4.45)>.49 && cueOpacity(cue,4.45)<.51);
  assert.equal(cueOpacity(cue,4.7),0);
});
const current:Identity={project:'komety-lyric-film',revision:'test-v1',inputs:{audio:'a',text:'b',focus:'c'},cueCount:2,cueIds:['one','two']};
const review:Review={...current,translationComplete:true,allSourceAndTargetSpansComplete:true,fullRecordingNormalSpeed:true,uncertainEventsReducedSpeed:true,nativeWideAndPortrait:true,noUnresolvedDefects:true,reviewerRole:'test-only',reviewedCueIds:['one','two']};
const approval:Approval={...current,productionAuthorized:true};
test('production boundary rejects missing, incomplete, stale and wrong-song review',()=>{
  assert.throws(()=>enforceProductionGate(current,null,approval),/missing/);
  assert.throws(()=>enforceProductionGate(current,review,null),/missing/);
  assert.throws(()=>enforceProductionGate(current,{...review,uncertainEventsReducedSpeed:false},approval),/required/);
  assert.throws(()=>enforceProductionGate(current,{...review,reviewedCueIds:['wrong','also-wrong']},approval),/required/);
  assert.throws(()=>enforceProductionGate(current,{...review,project:'other'},approval),/mismatched/);
  assert.throws(()=>enforceProductionGate(current,review,{...approval,revision:'old'}),/mismatched/);
  assert.throws(()=>enforceProductionGate(current,review,{...approval,inputs:{...current.inputs,text:'changed'}}),/mismatched/);
  assert.throws(()=>enforceProductionGate(current,review,{...approval,productionAuthorized:false}),/not authorized/);
  assert.doesNotThrow(()=>enforceProductionGate(current,review,approval));
});
