import type {ProductionData,Format} from './schema.ts';
import type {Layouts,Box} from './layout-types.ts';
import {activeSource,activeTargets,visibleCue} from './focus.ts';
import {palette as p} from './palette.ts';
import {geometry,lunarState,titleOpacity,spectrum,barPath} from './lunar-motion.ts';
export {spectrum} from './lunar-motion.ts';
export const escape=(s:string)=>s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/"/g,'&quot;');
export function sceneSvg(frame:number,format:Format,data:ProductionData,layouts:Layouts,bands:number[][]){
 const l=layouts[format],portrait=format==='portrait',w=l.width,h=l.height,g=geometry(portrait),m=lunarState(frame,data),asset=g.r/.397;
 const cue=visibleCue(data,frame),a=cue?activeSource(cue,frame,data):new Set<string>(),b=cue?activeTargets(cue,frame,data):new Set<string>();
 const lyric=(boxes:Box[],active:Set<string>,lang:string)=>'<g data-language="'+lang+'" font-family="LunarSans" font-weight="400" font-size="'+l.fontSize+'">'+boxes.map(word=>'<text data-word="'+word.id+'" x="'+word.x+'" y="'+word.y+'" fill="'+(active.has(word.id)?p.accent:p.ivory)+'">'+escape(word.text)+'</text>').join('')+'</g>';
 const layout=cue?l.cues[cue.id]:undefined,body=layout?lyric(layout.fr,a,'fr')+lyric(layout.en,b,'en'):'';
 const bars=spectrum(frame,bands,portrait).map((v,i)=>'<path data-band="'+i+'" d="'+barPath(i,v,portrait)+'" stroke="'+p.halo+'" stroke-width="'+(portrait?2.8:2.2)+'"/>').join('');
 // Fixed seeded star positions; no decorative flashing or free-running camera motion.
 const stars=Array.from({length:130},(_,i)=>{const x=((i*719+211)%1931)/1931*w,y=((i*367+29)%1093)/1093*(portrait?1100:700),r=i%17===0?1.9:1,opacity=i%17===0?.42:.17;return Math.hypot(x-g.cx,y-g.cy)>g.r+70?'<circle cx="'+x.toFixed(2)+'" cy="'+y.toFixed(2)+'" r="'+r+'" fill="'+p.ivory+'" opacity="'+opacity+'"/>':'';}).join('');
 const titleY=portrait?1310:826,creditY=portrait?1840:1035;
 return '<svg xmlns="http://www.w3.org/2000/svg" width="'+w+'" height="'+h+'" viewBox="0 0 '+w+' '+h+'"><defs><radialGradient id="atmosphere"><stop offset="0" stop-color="'+p.halo+'"/><stop offset=".55" stop-color="'+p.halo+'" stop-opacity=".38"/><stop offset="1" stop-color="'+p.ink+'" stop-opacity="0"/></radialGradient><radialGradient id="asset-fade"><stop offset=".8" stop-color="white"/><stop offset="1" stop-color="black"/></radialGradient><mask id="moon-mask"><circle cx="'+g.cx+'" cy="'+g.cy+'" r="'+asset/2+'" fill="url(#asset-fade)"/></mask><clipPath id="disc"><circle cx="'+g.cx+'" cy="'+g.cy+'" r="'+(g.r-2)+'"/></clipPath><linearGradient id="phase-shade"><stop offset="0" stop-color="'+p.ink+'"/><stop offset=".5" stop-color="'+p.ink+'" stop-opacity=".82"/><stop offset="1" stop-color="'+p.ink+'" stop-opacity="0"/></linearGradient></defs><rect width="'+w+'" height="'+h+'" fill="'+p.ink+'"/><g id="scene-content" opacity="'+m.fade.toFixed(4)+'">'+stars+'<circle id="moon-atmosphere" cx="'+g.cx+'" cy="'+g.cy+'" r="'+g.r*1.55+'" fill="url(#atmosphere)" opacity="'+m.haloOpacity.toFixed(4)+'"/><g id="moon-light" opacity="'+m.moonOpacity.toFixed(4)+'"><image href="/public/moon-v2.png" x="'+(g.cx-asset/2)+'" y="'+(g.cy-asset/2)+'" width="'+asset+'" height="'+asset+'" mask="url(#moon-mask)"/></g><rect id="moon-shade" x="'+(g.cx-g.r)+'" y="'+(g.cy-g.r)+'" width="'+g.r*2+'" height="'+g.r*2+'" clip-path="url(#disc)" fill="url(#phase-shade)" opacity="'+((1-m.reveal)*.88).toFixed(4)+'"/><g opacity=".63">'+bars+'</g><circle id="instrumental-ripple" cx="'+g.cx+'" cy="'+g.cy+'" r="'+(g.r+20+m.ripple.progress*38).toFixed(3)+'" fill="none" stroke="'+p.halo+'" stroke-width="2" opacity="'+m.ripple.opacity.toFixed(4)+'"/><g font-family="LunarSans" fill="'+p.ivory+'"><text x="'+(portrait?540:85)+'" y="'+(portrait?97:83)+'" text-anchor="'+(portrait?'middle':'start')+'" font-size="'+(portrait?27:25)+'" letter-spacing="5">L’IMPÉRATRICE</text><text x="'+(portrait?540:1835)+'" y="'+(portrait?151:83)+'" text-anchor="'+(portrait?'middle':'end')+'" font-size="'+(portrait?21:20)+'" letter-spacing="4" fill="'+p.muted+'">LA LUNE / ACOUSTIQUE</text></g><g id="title-layer" opacity="'+titleOpacity(frame,data).toFixed(4)+'" font-family="LunarSans" text-anchor="middle"><text x="'+w/2+'" y="'+titleY+'" font-size="'+(portrait?106:98)+'" letter-spacing="10" fill="'+p.accent+'">LA LUNE</text><text x="'+w/2+'" y="'+(titleY+(portrait?132:101))+'" font-size="'+(portrait?37:28)+'" letter-spacing="7" fill="'+p.ivory+'">THE MOON</text></g><g id="lyric-layer" data-cue="'+(cue?.id??'')+'">'+body+'</g><text x="'+w/2+'" y="'+creditY+'" text-anchor="middle" font-family="LunarSans" font-size="'+(portrait?18:16)+'" letter-spacing="3" fill="'+p.muted+'">L’IMPÉRATRICE · MICROQLIMA</text></g></svg>';
}
