import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {parseData} from '../src/schema.ts';import {activeTargets,frameAt} from '../src/focus.ts';import {checkGate} from '../src/production-gate.ts';
const data=parseData(JSON.parse(readFileSync('src/cues.json','utf8')));
test('Restrictive construction and reordered adjective preserve complete target meaning',()=>{const c=data.cues[4]!;for(const index of [5,7]){const w=c.fr[index]!;const set=activeTargets(c,frameAt((w.startSample+w.endSample)/2,data.sampleRate,60),data);assert.ok(set.has(c.en[6]!.id));}const scent=data.cues[2]!;assert.equal(scent.en[1]!.sourceIds[0],scent.fr[2]!.id);assert.equal(scent.en[2]!.sourceIds[0],scent.fr[1]!.id);});
test('All English grammatical expansions are source-linked',()=>{for(const c of data.cues)for(const w of c.en){assert.ok(w.sourceIds.length);for(const id of w.sourceIds)assert.ok(c.fr.some(s=>s.id===id));}assert.deepEqual(data.cues[8]!.en[1]!.sourceIds,data.cues[8]!.en[2]!.sourceIds);});
const identity={song:'p3E731cu_nE',revision:'fixture',hashes:{audio:'a'}},current={audio:'a'},ids=['one'];
const ready=()=>({song:identity.song,revision:identity.revision,inputHashes:{audio:'a'},actualAudioReviewComplete:true,translationReviewComplete:true,allCuesAllFormatsComplete:true,unresolvedDefects:[],cues:[{id:'one',meaning:true,normalAudio:true,slowAudio:true,landscape:true,portrait:true}],authorization:{approved:true,song:identity.song,revision:identity.revision,evidence:'test fixture only'}});
test('Production gate rejects missing, stale and incomplete evidence',()=>{assert.throws(()=>checkGate({},identity,current,ids));assert.throws(()=>checkGate({...ready(),song:'other'},identity,current,ids));assert.throws(()=>checkGate({...ready(),revision:'old'},identity,current,ids));assert.throws(()=>checkGate(ready(),identity,{audio:'changed'},ids));assert.throws(()=>checkGate({...ready(),actualAudioReviewComplete:false},identity,current,ids));assert.throws(()=>checkGate({...ready(),authorization:{approved:false}},identity,current,ids));assert.throws(()=>checkGate({...ready(),cues:[]},identity,current,ids));assert.equal(checkGate(ready(),identity,current,ids),true);});
test('Visual-revision scope cannot claim preview acceptance or change the approved timeline',()=>{
 const paths=['public/soundtrack.m4a','source/lyrics-fr.json','source/translation.json','src/cues.json','src/layout.json','src/focus.ts'];
 const hashes=Object.fromEntries(paths.map(p=>[p,p+'-fixture'])),i={song:'p3E731cu_nE',revision:'preview-v3-celestial',hashes};
 const auth={song:i.song,previewRevision:i.revision,authorizationId:'la-lune-v3-celestial-2026-09-18',previewAccepted:false,fullRenderAuthorized:true,visualCorrectionDeliveryRequested:true,celestialAuditComplete:true,priorApprovedHashes:hashes};
 const r={...ready(),song:i.song,revision:i.revision,inputHashes:hashes,status:'authorized-visual-revision',reviewMode:'owner-directed-visual-revision',actualAudioReviewComplete:false,allCuesAllFormatsComplete:false,finalTechnicalAuditComplete:true,authorization:{approved:true,song:i.song,revision:i.revision},acceptance:{authorizationId:auth.authorizationId,evidenceBasis:'Scoped fixture',coverageLimit:'Listening remains unclaimed'}};
 assert.equal(checkGate(r,i,hashes,ids,auth),true);
 for(const change of [{previewAccepted:true},{fullRenderAuthorized:false},{visualCorrectionDeliveryRequested:false},{celestialAuditComplete:false},{authorizationId:'other'},{priorApprovedHashes:{}}])assert.throws(()=>checkGate(r,i,hashes,ids,{...auth,...change}));
 const changed={...hashes,'src/cues.json':'new-timing'};assert.throws(()=>checkGate({...r,inputHashes:changed},{...i,hashes:changed},changed,ids,auth));
});
