import {readFileSync,writeFileSync,statSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {parseData} from '../src/schema.ts';
const hash=(bytes:Uint8Array)=>createHash('sha256').update(bytes).digest('hex');
const file=(path:string)=>({path,bytes:statSync(path).size,sha256:hash(readFileSync(path))});
const data=parseData(JSON.parse(readFileSync('src/cues.json','utf8')));
const packets=(path:string)=>JSON.parse(execFileSync('ffprobe',['-v','error','-select_streams','a:0','-show_packets','-show_data_hash','sha256','-show_entries','packet=pts,dts,duration,size,data_hash','-of','json',path],{encoding:'utf8',maxBuffer:12000000})).packets;
const original=packets('public/soundtrack.m4a'),preview=packets('public/review-source.mp4');
if(JSON.stringify(original)!==JSON.stringify(preview))throw Error('Review remux changed AAC packets or timestamps');
const decoded=execFileSync('ffmpeg',['-v','error','-i','public/soundtrack.m4a','-ac','2','-ar','44100','-f','f32le','pipe:1'],{maxBuffer:100000000});
if(decoded.length/8!==data.sampleCount)throw Error('Decoded sample count differs');
const assets=['public/soundtrack.m4a','public/footage.mp4','public/original-4k.webm','public/review-source.mp4','public/CormorantGaramond-Semibold.ttf','public/CormorantGaramond-OFL.txt','source/supplied-lyrics.txt','source/original.txt','source/text-and-mapping.json'].map(file);
const manifest={project:'Anya Nami — Sugar Glass',source:'https://www.youtube.com/watch?v=-NsQ8_WLq2s',sourceTitle:'Anya Nami - Sugar Glass (mood video)',sourceAuthor:'Anya Nami',sourceDescription:'No description returned by the metadata endpoint.',sourceFormats:{originalPicture:'313: VP9 3840×2160, 25 fps',reviewPicture:'137: AVC 1920×1080, 25 fps',lockedAudio:'140: AAC LC, 44100 Hz stereo'},audio:{sampleRate:data.sampleRate,sampleCount:data.sampleCount,duration:data.duration,decodedPcmSha256:hash(decoded),timeZero:'first decoded PCM sample',gain:'unchanged',initialPadding:0,reviewPacketIdentity:true,aacPackets:original.length},display:{fps:data.fps,frames:data.frames,formats:[[1920,1080],[1080,1920]],sourceCadence:25},tools:{node:process.version,typescript:'7.0.2 (stable registry tag verified for this project)',ffmpeg:execFileSync('ffmpeg',['-version'],{encoding:'utf8'}).split('\n')[0]},assets,status:{preview:'available',synchronization:'incomplete — actual-audio review pending',production:'not authorized; no production capture or encoding performed',publication:'source and workflow only; full media kept local'}};
writeFileSync('source/input-manifest.json',JSON.stringify(manifest,null,2)+'\n');
const geometry=JSON.parse(readFileSync('evidence/browser-geometry.json','utf8'));
if(geometry.status!=='passed')throw Error('Browser geometry must pass');
const result={status:'preview technically verified; listening review pending',revision:'preview-v1',cues:data.cues.length,sourceWords:data.cues.reduce((n,c)=>n+c.source.length,0),targetWords:data.cues.reduce((n,c)=>n+c.target.length,0),compositions:['SugarGlassLandscape','SugarGlassPortrait'],frames:data.frames,selectedBoundaryReviewRequired:data.cues.flatMap(c=>c.source).filter(w=>w.reviewRequired).length,checks:{strictTypeScript:true,testsPassed:7,completeSourceDecode:true,aacPacketAndTimestampIdentity:true,decodedSampleCount:data.sampleCount,productionGateNegativeControl:'render refuses before output creation',browserGeometry:geometry,modelChecksAreActualListening:false},actualAudioReviewComplete:false,productionRenderAuthorized:false,fullFilmRendered:false};
writeFileSync('evidence/preview-verification.json',JSON.stringify(result,null,2)+'\n');
console.log(JSON.stringify({aacPackets:original.length,decodedSamples:data.sampleCount,geometry:geometry.status,production:'blocked'}));
