import {execFileSync} from 'node:child_process';
import {readFileSync,writeFileSync,statSync,createReadStream} from 'node:fs';
import {createHash} from 'node:crypto';
const hash=async(path:string)=>{const h=createHash('sha256');for await(const b of createReadStream(path))h.update(b);return h.digest('hex');};
const inputs=[];
for(const path of ['source/source.mkv','source/soundtrack.opus','source/artist-cover.jpg','public/soundtrack.m4a','src/cues.json','analysis/lyrics-user-ru.txt','public/Oswald-Bold.ttf','public/Oswald-Medium.ttf','public/SpaceGrotesk.ttf','public/Oswald-OFL.txt','public/SpaceGrotesk-OFL.txt'])inputs.push({path,bytes:statSync(path).size,sha256:await hash(path)});
const manifest={version:1,track:'ray! — Пожары',sourceUrl:'https://www.youtube.com/watch?v=ml9TqzvJLCg',releaseUrl:'https://hangov3r.band.link/pojari',artistChannel:'https://www.youtube.com/channel/UC5x2GKvVvMUvCp7bKIzY23Q',published:'2026-09-10',retrieved:'2026-09-11',sourceVideo:{width:1920,height:1080,fps:30,codec:'av1',formatId:'399',decodedFrames:4500,visualContent:'Stationary official release photograph with blurred side fill. 4500 frames scanned at 160×90; differences are primarily compression variation.'},sourceAudio:{codec:'opus',formatId:'251',sampleRate:48000,channels:2,retainedDecodedSamples:7200648,durationSeconds:150.0135},delivery:{fps:60,frames:9001,videoDurationSeconds:9001/60,audio:'AAC 320k, -3.2 dB gain, no temporal edit; identical packets in both final films',dimensions:[[1920,1080],[1080,1920]]},artwork:{source:'https://is1-ssl.mzstatic.com/image/thumb/Music221/v4/aa/0e/ad/aa0ead8b-6fd7-ddd9-07d8-1818e3d46fe2/0.jpg/3000x3000bb.jpg',discovery:'Linked official release page; higher-resolution version of the same photograph',width:3000,height:3000,photographer:'Not independently identified',filmTreatment:'Original photograph with crop, gradients and added 60fps motion; no generated replacement inside the film',coverTreatment:'Separate AI-assisted adaptations of the source photo; generated-image model version not exposed'},credits:{artist:'ray!',lyrics:'Чистякова-Ионова Лидия Александровна',music:['Чистякова-Ионова Лидия Александровна','Багиров Гейдар Анвер Оглы'],authority:'Credits transcribed from the artist upload description'},inputs,runtime:{node:process.version,chromiumOriginalRun:'Google Chrome for Testing 149.0.7790.0',ffmpeg:execFileSync('ffmpeg',['-version']).toString().split('\n')[0],packages:JSON.parse(readFileSync('package.json','utf8'))},rights:'Music, lyrics, recording, photograph and source-derived covers remain third-party material, excluded from the repository CC BY 4.0 grant. No ownership or endorsement claim.'};
writeFileSync('source.json',JSON.stringify(manifest,null,2));
const coverRows=[];for(const kind of ['YouTube','TikTok']){const file=`output/Pozhary-${kind==='YouTube'?'YouTube-Thumbnail-1920x1080':'TikTok-Cover-Profile-1200x1600'}.jpg`;const probe=JSON.parse(execFileSync('ffprobe',['-v','error','-show_streams','-of','json',file]).toString());coverRows.push({file:file.split('/').at(-1),width:probe.streams[0].width,height:probe.streams[0].height,bytes:statSync(file).size,sha256:await hash(file)});}
writeFileSync('evidence/cover-verification.json',JSON.stringify({method:'Built-in image generation with official source photograph as reference; FFmpeg Lanczos normalization and JPEG export. Exact prompts and generated originals retained.',imageModel:'Not disclosed by tool',assets:coverRows,checks:{exactSpelling:true,titleAndArtistReadableAt150x200:true,portrait300x400Reviewed:true,centerCropRemovingFivePercentEachEdgeReviewed:true,youtube320x180Reviewed:true,letterboxing:false,uploadInterfaceReview:'Local simulations only; no live upload performed.'}},null,2));
