import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {parseData} from '../src/schema.ts';import {activeSource,activeTargets,frameAt,targetFocusIds} from '../src/focus.ts';import {checkGate} from '../src/production-gate.ts';
const data=parseData(JSON.parse(readFileSync('src/cues.json','utf8')));
test('Every English word follows exactly its declared complete focus interval union, including releases',()=>{for(const c of data.cues)for(let f=frameAt(c.startSample,data.sampleRate,60)-1;f<=frameAt(c.endSample,data.sampleRate,60)+1;f++){const es=activeSource(c,f,data),en=activeTargets(c,f,data);for(const w of c.en)assert.equal(en.has(w.id),targetFocusIds(w).some(id=>es.has(id)),c.id+' '+w.text+' '+f);}});
const meaning=(id:string)=>{const c=data.cues.find(c=>c.es.some(w=>w.id===id));assert.ok(c);return c.en.filter(w=>w.sourceIds.includes(id)).map(w=>w.text).join(' ');};
test('Reordered adjectives, explicit negation and complete expansions retain their own source events',()=>{assert.equal(meaning('P016-s05'),'golden');assert.equal(meaning('P016-s04'),'boy.');assert.equal(meaning('P014-s03'),"don't");assert.equal(meaning('P014-s04'),'I want');assert.equal(meaning('P023-s02'),'to seek you');assert.equal(meaning('P023-s08'),'seek myself');assert.equal(meaning('P051-s03'),'tremble,');});
test('Live repeats and final sustained vowel are retained without copied timestamps',()=>{assert.equal(data.cues.filter(c=>c.section==='Opening refrain').length,8);for(const section of ['First returning refrain','Middle returning refrain','Final returning refrain']){const rows=data.cues.filter(c=>c.section===section);assert.equal(rows.length,8);assert.equal(rows.at(-1)?.es.map(w=>w.text).join(' '),'Que sos el muchacho');}const last=data.cues.find(c=>c.es.some(w=>w.id==='P054-s02'));assert.ok(last);const word=last.es.find(w=>w.id==='P054-s02');assert.ok(word);assert.ok(word.startSample/data.sampleRate<261.6);assert.ok(word.endSample/data.sampleRate>265);assert.equal(meaning(word.id),'still');assert.equal(data.cues.at(-1)?.es.map(w=>w.text).join(' '),'Esto se acabó');});
const identity={song:'uvLVcEBIn-4',revision:'fixture',hashes:{audio:'a'}},current={audio:'a'},ids=['one'];
const ready=()=>({song:identity.song,revision:identity.revision,inputHashes:{audio:'a'},actualAudioReviewComplete:true,translationReviewComplete:true,allCuesAllFormatsComplete:true,unresolvedDefects:[],cues:[{id:'one',meaning:true,normalAudio:true,slowAudio:true,landscape:true,portrait:true}],authorization:{approved:true,song:identity.song,revision:identity.revision,evidence:'Synthetic fixture only'}});
test('Production refuses missing authorization, stale revision and incomplete listening',()=>{assert.throws(()=>checkGate({},identity,current,ids));assert.throws(()=>checkGate({...ready(),song:'other'},identity,current,ids));assert.throws(()=>checkGate({...ready(),revision:'old'},identity,current,ids));assert.throws(()=>checkGate(ready(),identity,{audio:'changed'},ids));assert.throws(()=>checkGate({...ready(),actualAudioReviewComplete:false},identity,current,ids));assert.throws(()=>checkGate({...ready(),authorization:{approved:false}},identity,current,ids));assert.throws(()=>checkGate({...ready(),cues:[]},identity,current,ids));assert.throws(()=>checkGate({...ready(),unresolvedDefects:['a defect']},identity,current,ids));assert.equal(checkGate(ready(),identity,current,ids),true);});

test('Cue beginnings use sentence case while internal words retain normal Spanish and English spelling',()=>{for(const c of data.cues)for(const language of (['es','en'] as const)){const text=c[language].map(w=>w.text).join(' ');const first=text.match(/\p{L}/u)?.[0];assert.ok(first);assert.equal(first,first.toLocaleUpperCase(language),c.id+' '+language);}const all=data.cues.flatMap(c=>c.es).map(w=>w.text.toLowerCase().replace(/[.,!?]+$/g,''));for(const word of ['párpado','estadía','compañía','robó','sumás','aumentás'])assert.ok(all.includes(word),word);});
