import {createCanvas,loadImage} from '@napi-rs/canvas';import type {Canvas,Image} from '@napi-rs/canvas';import {readFileSync} from 'node:fs';import {parseData} from '../src/schema.ts';import type {Format} from '../src/schema.ts';import type {Layouts,Box} from '../src/layout-types.ts';import {palette} from '../src/palette.ts';import {decorOpacity,spectrum,clamp} from '../src/scene.ts';import {visibleCue,activeSource,activeTargets} from '../src/focus.ts';
const data=parseData(JSON.parse(readFileSync('src/cues.json','utf8'))),layouts=JSON.parse(readFileSync('src/layout.json','utf8')) as Layouts,bands=JSON.parse(readFileSync('public/science.json','utf8')) as number[][];
type Entry={key:string;file:string;x:number;y:number;width:number;height:number};
export async function compositor(format:Format){const l=layouts[format],root='output/raster-cache/'+format,inventory=JSON.parse(readFileSync(root+'/inventory.json','utf8')) as {entries:Entry[]};const canvas=createCanvas(l.width*2,l.height*2),ctx=canvas.getContext('2d'),overlay=createCanvas(canvas.width,canvas.height),o=overlay.getContext('2d'),lyric=createCanvas(canvas.width,canvas.height),lc=lyric.getContext('2d'),picture=createCanvas(canvas.width,canvas.height),pc=picture.getContext('2d');const metadata=inventory.entries.find(e=>e.key==='metadata')!;const title=await loadImage(root+'/'+metadata.file);let lastCue:string|undefined,lastFocus='';let idle:Image|undefined,active:Image|undefined,idleEntry:Entry|undefined,activeEntry:Entry|undefined;
 const gradient=o.createLinearGradient(0,0,0,canvas.height);for(const [stop,alpha] of [[0,.6],[.23,0],[.44,.04],[.64,.74],[.8,.97],[1,1]])gradient.addColorStop(stop!,`rgba(13,9,11,${alpha})`);
 function clipBox(word:Box,boxes:Box[]){const row=boxes.filter(w=>w.y===word.y).sort((a,b)=>a.x-b.x),index=row.findIndex(w=>w.id===word.id),prev=row[index-1],next=row[index+1];const left=prev?(prev.x+prev.width+word.x)/2:word.x-14,right=next?(word.x+word.width+next.x)/2:word.x+word.width+14;const rows=[...new Set(boxes.map(w=>w.y))].sort((a,b)=>a-b),ri=rows.indexOf(word.y),above=rows[ri-1],below=rows[ri+1],top=above===undefined?word.y-l.fontSize-16:(above+word.y)/2-l.fontSize*.25,bottom=below===undefined?word.y+l.fontSize*.5+16:(word.y+below)/2-l.fontSize*.25;return {x:Math.floor(left*2),y:Math.floor(top*2),w:Math.ceil(right*2)-Math.floor(left*2),h:Math.ceil(bottom*2)-Math.floor(top*2)};}
 return {canvas,overlay,async paint(frame:number,source?:Canvas|Image){const t=frame/data.fps,alpha=decorOpacity(t),cue=visibleCue(data,frame);o.clearRect(0,0,overlay.width,overlay.height);o.globalAlpha=alpha;if(format==='landscape'){o.fillStyle=gradient;o.fillRect(0,0,overlay.width,overlay.height);}o.drawImage(title,metadata.x,metadata.y);o.globalAlpha=1;
 if(cue){const focus=[...activeSource(cue,frame,data),...activeTargets(cue,frame,data)].sort().join(',');if(cue.id!==lastCue){idleEntry=inventory.entries.find(e=>e.key===cue.id+'-idle')!;activeEntry=inventory.entries.find(e=>e.key===cue.id+'-active')!;idle=await loadImage(root+'/'+idleEntry.file);active=await loadImage(root+'/'+activeEntry.file);lastCue=cue.id;lastFocus='unset';}if(focus!==lastFocus){lc.clearRect(0,0,lyric.width,lyric.height);lc.drawImage(idle!,idleEntry!.x,idleEntry!.y);const ids=new Set(focus.split(',')),geo=l.cues[cue.id]!;for(const lane of [geo.es,geo.en])for(const word of lane)if(ids.has(word.id)){const box=clipBox(word,lane);lc.save();lc.beginPath();lc.rect(box.x,box.y,box.w,box.h);lc.clip();lc.clearRect(box.x,box.y,box.w,box.h);lc.drawImage(active!,activeEntry!.x,activeEntry!.y);lc.restore();}lastFocus=focus;}o.drawImage(lyric,0,0);}
 const portrait=format==='portrait',heights=spectrum(frame,bands,portrait),step=portrait?12:11,bw=portrait?5:4,origin=(l.width-step*63-bw)/2,base=portrait?1760:1050;o.globalAlpha=alpha*.68;o.fillStyle=palette.active;for(let i=0;i<heights.length;i++)o.fillRect((origin+i*step)*2,(base-heights[i]!)*2,bw*2,heights[i]!*2);o.globalAlpha=1;
 ctx.globalAlpha=1;ctx.fillStyle=palette.ink;ctx.fillRect(0,0,canvas.width,canvas.height);if(source){if(portrait){pc.clearRect(0,0,picture.width,picture.height);pc.globalCompositeOperation='source-over';pc.drawImage(source,0,620,2160,1215);pc.globalCompositeOperation='destination-in';const edge=clamp((t-285.6)/1.4),mask=pc.createLinearGradient(0,620,0,1835);mask.addColorStop(0,`rgba(0,0,0,${edge})`);mask.addColorStop(.04,'black');mask.addColorStop(.84,'black');mask.addColorStop(1,`rgba(0,0,0,${edge})`);pc.fillStyle=mask;pc.fillRect(0,620,2160,1215);pc.globalCompositeOperation='source-over';ctx.drawImage(picture,0,0);}else ctx.drawImage(source,0,0,canvas.width,canvas.height);}ctx.drawImage(overlay,0,0);return canvas;}};
}
