import {spawn} from 'node:child_process';import {once} from 'node:events';import {createCanvas,ImageData} from '@napi-rs/canvas';import {readFileSync,writeFileSync,mkdirSync,existsSync,createReadStream,statfsSync} from 'node:fs';import {createHash} from 'node:crypto';import {compositor} from './raster-compose.ts';import {verifyCache} from './raster-contract.ts';import {assertProductionGate,assertPreviewAuthorization,inputHashes} from './production-contract.ts';import {parseData} from '../src/schema.ts';
const arg=(k:string,d:string)=>{const i=process.argv.indexOf(k);return i<0?d:process.argv[i+1]??d;};const production=process.argv.includes('--production'),diagnostic=process.argv.includes('--diagnostic');if(production===diagnostic)throw Error('Choose explicit production or diagnostic');if(production)assertProductionGate();else assertPreviewAuthorization();const format=arg('--format','landscape');if(format!=='landscape'&&format!=='portrait')throw Error('Unknown format');const cache=verifyCache(format),data=parseData(JSON.parse(readFileSync('src/cues.json','utf8'))),width=format==='landscape'?1920:1080,height=format==='landscape'?1080:1920;
const hash=async(p:string)=>{const h=createHash('sha256');for await(const b of createReadStream(p))h.update(b);return h.digest('hex');};const write=(p:string,x:unknown)=>writeFileSync(p,JSON.stringify(x,null,2)+'\n');const run=(args:string[])=>new Promise<void>((ok,fail)=>{const c=spawn('ffmpeg',args,{stdio:'inherit'});c.on('error',fail);c.on('close',code=>code===0?ok():fail(Error('ffmpeg '+code)));});
const root=`output/${format}-segments`;mkdirSync(root,{recursive:true});mkdirSync('evidence/production',{recursive:true});const fingerprint=createHash('sha256').update(JSON.stringify(production?inputHashes():cache.inputs)).update(JSON.stringify(cache)).update('live-rgba2x-60fps-round-up-lanczos-vt24m-v2').digest('hex'),started=Date.now(),parts=production?16:1,chunks=[];const status=(x:Record<string,unknown>)=>write(`evidence/production/${format}-status.json`,{format,elapsedSeconds:(Date.now()-started)/1000,...x});
const firstDiagnostic=Math.round(Number(arg('--start','107.8'))*60),count=Number(arg('--frames','180'));if(diagnostic&&(!Number.isSafeInteger(firstDiagnostic)||firstDiagnostic<0||!Number.isSafeInteger(count)||count<1||count>1200))throw Error('Invalid diagnostic interval');
const c=await compositor(format),source=createCanvas(1920,1080),s=source.getContext('2d');const sourceBytes=1920*1080*4;
for(let part=0;part<parts;part++){if(production)assertProductionGate();else assertPreviewAuthorization();const disk=statfsSync('.');if(disk.bavail*disk.bsize<5e9)throw Error('Insufficient disk space');const first=production?Math.floor(part*data.frames/parts):firstDiagnostic,last=production?Math.floor((part+1)*data.frames/parts)-1:Math.min(data.frames-1,first+count-1),stem=production?'part-'+String(part+1).padStart(2,'0'):'diagnostic',output=root+'/'+stem+'.mp4',receipt=output+'.json';let cached=false;if(existsSync(output)&&existsSync(receipt)){const r=JSON.parse(readFileSync(receipt,'utf8'));cached=r.fingerprint===fingerprint&&r.first===first&&r.last===last&&r.sha256===await hash(output);}if(!cached){
const decoder=spawn('ffmpeg',['-v','error','-threads','2','-i','public/source.mp4','-an','-vf',`fps=60:round=up,tpad=stop_mode=clone:stop_duration=0.2,trim=start_frame=${first}:end_frame=${last+1},setpts=N/(60*TB)`,'-pix_fmt','rgba','-f','rawvideo','pipe:1'],{stdio:['ignore','pipe','pipe']});let decodeError='';decoder.stderr.on('data',b=>decodeError+=b);const decoderClosed=once(decoder,'close');
const encoder=spawn('ffmpeg',['-v','error','-y','-f','rawvideo','-pixel_format','rgba','-video_size',`${width*2}x${height*2}`,'-framerate','60','-i','pipe:0','-an','-vf',`scale=${width}:${height}:flags=lanczos:out_color_matrix=bt709:out_range=tv,setsar=1,format=p010le`,'-c:v','hevc_videotoolbox','-profile:v','main10','-b:v','24M','-maxrate','32M','-bufsize','48M','-allow_sw','0','-g','120','-tag:v','hvc1','-colorspace','bt709','-color_trc','bt709','-color_primaries','bt709','-color_range','tv','-video_track_timescale','60000',output],{stdio:['pipe','inherit','inherit']});const encoderClosed=once(encoder,'close');let writeError:Error|undefined;encoder.stdin.on('error',e=>{writeError=e;decoder.kill('SIGTERM');});
let frame=first,filled=0,tick=0;const buffer=Buffer.allocUnsafe(sourceBytes),rawHash=createHash('sha256');try{for await(const bytes of decoder.stdout){let offset=0;while(offset<bytes.length){const n=Math.min(sourceBytes-filled,bytes.length-offset);bytes.copy(buffer,filled,offset,offset+n);filled+=n;offset+=n;if(filled===sourceBytes){if(writeError)throw writeError;s.putImageData(new ImageData(new Uint8ClampedArray(buffer.buffer,buffer.byteOffset,buffer.length),1920,1080),0,0);const canvas=await c.paint(frame,source),out=canvas.data();rawHash.update(out);await new Promise<void>((ok,fail)=>encoder.stdin.write(out,error=>error?fail(error):ok()));frame++;filled=0;if(frame%60===0)global.gc?.();if(Date.now()-tick>10000){tick=Date.now();status({phase:'Compositing and encoding',segment:part+1,segments:parts,frames:frame,totalFrames:data.frames});console.log(format,frame+'/'+data.frames,'segment',part+1+'/'+parts);}}}}encoder.stdin.end();const [dc]=await decoderClosed,[ec]=await encoderClosed;if(dc!==0||ec!==0||filled||frame!==last+1)throw Error('Incomplete segment '+dc+'/'+ec+' '+frame+' '+decodeError);}catch(error){decoder.kill('SIGTERM');encoder.kill('SIGTERM');throw error;}
await run(['-v','error','-xerror','-err_detect','explode','-threads','3','-i',output,'-f','null','-']);write(receipt,{fingerprint,first,last,frames:last-first+1,rawRgbaSha256:rawHash.digest('hex'),sha256:await hash(output),method:'Original video sample-and-hold at 60 fps; 2× exact Chromium text layers and deterministic composition; one Lanczos downsample; HEVC Main10 VideoToolbox 24 Mb/s target'});
}chunks.push({file:stem+'.mp4',first,last});if(production&&!cached&&process.argv.includes('--one-segment')&&part<parts-1){console.log('Isolated segment complete');process.exit(0);}}
if(production){assertProductionGate();const list=root+'/concat.txt';writeFileSync(list,chunks.map(c=>`file '${c.file}'\nduration ${((Math.round((c.last+1)*1e6/60)-Math.round(c.first*1e6/60))/1e6).toFixed(6)}`).join('\n')+'\n');const output=`output/Pero-es-locura-${format}-${width}x${height}-60fps.mp4`;await run(['-v','error','-y','-f','concat','-safe','0','-i',list,'-i','public/soundtrack.m4a','-map','0:v:0','-map','1:a:0','-c','copy','-tag:v','hvc1','-video_track_timescale','60000','-movflags','+faststart',output]);write(`evidence/production/${format}-capture.json`,{fingerprint,format,frames:data.frames,chunks,cache,output,sha256:await hash(output),elapsedSeconds:(Date.now()-started)/1000});status({phase:'Rendered; verification pending',frames:data.frames,totalFrames:data.frames,output});console.log(output);}else console.log('Diagnostic encoded:',root+'/diagnostic.mp4');
