// Generated by analysis/build_shots.py from reviewed segment overrides. Do not hand-edit;
// change the override tables there and regenerate. Times are source seconds (frame × 1001/24000).
export type PortraitFrame = {mode: 'crop'; x: number; x2?: number} | {mode: 'fit'};
export type Shot = {id: string; start: number; end: number; frames: [number, number]; portrait: PortraitFrame; zone: 'lower' | 'bottom' | 'upper'; protect: boolean};
export const SHOTS: readonly Shot[] = [
  {id: 'S001', start: 0.000000, end: 7.048708, frames: [0, 169], portrait: {mode: 'crop', x: 0.497}, zone: 'lower', protect: true}, // segments 0,1,2
  {id: 'S002', start: 7.048708, end: 14.514500, frames: [169, 348], portrait: {mode: 'crop', x: 0.499}, zone: 'lower', protect: false}, // segments 3,4,5,6
  {id: 'S003', start: 14.514500, end: 15.432083, frames: [348, 370], portrait: {mode: 'crop', x: 0.456}, zone: 'lower', protect: false}, // segments 7
  {id: 'S004', start: 15.432083, end: 22.522500, frames: [370, 540], portrait: {mode: 'crop', x: 0.506}, zone: 'lower', protect: false}, // segments 8,9
  {id: 'S005', start: 22.522500, end: 24.441083, frames: [540, 586], portrait: {mode: 'crop', x: 0.431}, zone: 'lower', protect: false}, // segments 10
  {id: 'S006', start: 24.441083, end: 28.528500, frames: [586, 684], portrait: {mode: 'crop', x: 0.494}, zone: 'lower', protect: false}, // segments 11,12
  {id: 'S007', start: 28.528500, end: 33.074708, frames: [684, 793], portrait: {mode: 'fit'}, zone: 'lower', protect: true}, // segments 13,14
  {id: 'S008', start: 33.074708, end: 34.242542, frames: [793, 821], portrait: {mode: 'crop', x: 0.475}, zone: 'lower', protect: false}, // segments 15
  {id: 'S009', start: 34.242542, end: 37.162125, frames: [821, 891], portrait: {mode: 'fit'}, zone: 'lower', protect: true}, // segments 16,17,18
  {id: 'S010', start: 37.162125, end: 37.871167, frames: [891, 908], portrait: {mode: 'crop', x: 0.521}, zone: 'lower', protect: false}, // segments 19
  {id: 'S011', start: 37.871167, end: 38.413375, frames: [908, 921], portrait: {mode: 'crop', x: 0.58}, zone: 'lower', protect: false}, // segments 20
  {id: 'S012', start: 38.413375, end: 39.956583, frames: [921, 958], portrait: {mode: 'crop', x: 0.488}, zone: 'lower', protect: false}, // segments 21
  {id: 'S013', start: 39.956583, end: 41.583208, frames: [958, 997], portrait: {mode: 'crop', x: 0.433}, zone: 'lower', protect: false}, // segments 22
  {id: 'S014', start: 41.583208, end: 42.959583, frames: [997, 1030], portrait: {mode: 'crop', x: 0.502}, zone: 'lower', protect: false}, // segments 23
  {id: 'S015', start: 42.959583, end: 48.590208, frames: [1030, 1165], portrait: {mode: 'crop', x: 0.45}, zone: 'lower', protect: false}, // segments 24,25
  {id: 'S016', start: 48.590208, end: 48.757042, frames: [1165, 1169], portrait: {mode: 'crop', x: 0.453, x2: 0.515}, zone: 'lower', protect: false}, // segments 26
  {id: 'S017', start: 48.757042, end: 49.132417, frames: [1169, 1178], portrait: {mode: 'crop', x: 0.515, x2: 0.478}, zone: 'lower', protect: false}, // segments 27
  {id: 'S018', start: 49.132417, end: 50.467083, frames: [1178, 1210], portrait: {mode: 'crop', x: 0.478}, zone: 'lower', protect: false}, // segments 28,29
  {id: 'S019', start: 50.467083, end: 50.633917, frames: [1210, 1214], portrait: {mode: 'crop', x: 0.497, x2: 0.497}, zone: 'lower', protect: false}, // segments 30
  {id: 'S020', start: 50.633917, end: 58.767042, frames: [1214, 1409], portrait: {mode: 'crop', x: 0.497}, zone: 'lower', protect: false}, // segments 31,32,33,34
  {id: 'S021', start: 58.767042, end: 59.225833, frames: [1409, 1420], portrait: {mode: 'crop', x: 0.439}, zone: 'upper', protect: false}, // segments 35
  {id: 'S022', start: 59.225833, end: 62.520792, frames: [1420, 1499], portrait: {mode: 'fit'}, zone: 'upper', protect: true}, // segments 36
  {id: 'S023', start: 62.520792, end: 64.773042, frames: [1499, 1553], portrait: {mode: 'crop', x: 0.499}, zone: 'lower', protect: false}, // segments 37
  {id: 'S024', start: 64.773042, end: 68.902167, frames: [1553, 1652], portrait: {mode: 'crop', x: 0.456}, zone: 'lower', protect: false}, // segments 38,39,40
  {id: 'S025', start: 68.902167, end: 69.069000, frames: [1652, 1656], portrait: {mode: 'crop', x: 0.486, x2: 0.491}, zone: 'lower', protect: false}, // segments 41
  {id: 'S026', start: 69.069000, end: 71.529792, frames: [1656, 1715], portrait: {mode: 'crop', x: 0.491}, zone: 'lower', protect: false}, // segments 42,43
  {id: 'S027', start: 71.529792, end: 72.614208, frames: [1715, 1741], portrait: {mode: 'crop', x: 0.62}, zone: 'lower', protect: false}, // segments 44
  {id: 'S028', start: 72.614208, end: 72.781042, frames: [1741, 1745], portrait: {mode: 'crop', x: 0.62, x2: 0.63}, zone: 'lower', protect: false}, // segments 45
  {id: 'S029', start: 72.781042, end: 78.453375, frames: [1745, 1881], portrait: {mode: 'crop', x: 0.63, x2: 0.45}, zone: 'lower', protect: false}, // segments 46
  {id: 'S030', start: 78.453375, end: 78.661917, frames: [1881, 1886], portrait: {mode: 'crop', x: 0.45, x2: 0.507}, zone: 'lower', protect: false}, // segments 47
  {id: 'S031', start: 78.661917, end: 79.871458, frames: [1886, 1915], portrait: {mode: 'crop', x: 0.507}, zone: 'lower', protect: false}, // segments 48,49
  {id: 'S032', start: 79.871458, end: 80.121708, frames: [1915, 1921], portrait: {mode: 'crop', x: 0.494, x2: 0.502}, zone: 'lower', protect: false}, // segments 50
  {id: 'S033', start: 80.121708, end: 80.288542, frames: [1921, 1925], portrait: {mode: 'crop', x: 0.502}, zone: 'lower', protect: false}, // segments 51
  {id: 'S034', start: 80.288542, end: 83.583500, frames: [1925, 2004], portrait: {mode: 'fit'}, zone: 'lower', protect: true}, // segments 52,53
  {id: 'S035', start: 83.583500, end: 84.876458, frames: [2004, 2035], portrait: {mode: 'crop', x: 0.504}, zone: 'lower', protect: false}, // segments 54
  {id: 'S036', start: 84.876458, end: 85.210125, frames: [2035, 2043], portrait: {mode: 'crop', x: 0.504, x2: 0.499}, zone: 'lower', protect: false}, // segments 55
  {id: 'S037', start: 85.210125, end: 85.710625, frames: [2043, 2055], portrait: {mode: 'crop', x: 0.499}, zone: 'lower', protect: false}, // segments 56
  {id: 'S038', start: 85.710625, end: 87.754333, frames: [2055, 2104], portrait: {mode: 'crop', x: 0.62}, zone: 'upper', protect: true}, // segments 57
  {id: 'S039', start: 87.754333, end: 88.088000, frames: [2104, 2112], portrait: {mode: 'crop', x: 0.62, x2: 0.587}, zone: 'lower', protect: false}, // segments 58
  {id: 'S040', start: 88.088000, end: 88.922167, frames: [2112, 2132], portrait: {mode: 'crop', x: 0.587}, zone: 'lower', protect: false}, // segments 59
  {id: 'S041', start: 88.922167, end: 91.049292, frames: [2132, 2183], portrait: {mode: 'fit'}, zone: 'lower', protect: true}, // segments 60
  {id: 'S042', start: 91.049292, end: 94.511083, frames: [2183, 2266], portrait: {mode: 'crop', x: 0.483}, zone: 'lower', protect: false}, // segments 61
  {id: 'S043', start: 94.511083, end: 95.512083, frames: [2266, 2290], portrait: {mode: 'crop', x: 0.543}, zone: 'lower', protect: false}, // segments 62
  {id: 'S044', start: 95.512083, end: 99.766333, frames: [2290, 2392], portrait: {mode: 'crop', x: 0.58}, zone: 'lower', protect: false}, // segments 63
  {id: 'S045', start: 99.766333, end: 108.900458, frames: [2392, 2611], portrait: {mode: 'crop', x: 0.489}, zone: 'lower', protect: false}, // segments 64,65
  {id: 'S046', start: 108.900458, end: 109.442667, frames: [2611, 2624], portrait: {mode: 'fit'}, zone: 'lower', protect: true}, // segments 66
  {id: 'S047', start: 109.442667, end: 110.527083, frames: [2624, 2650], portrait: {mode: 'crop', x: 0.491}, zone: 'lower', protect: false}, // segments 67
  {id: 'S048', start: 110.527083, end: 111.861750, frames: [2650, 2682], portrait: {mode: 'crop', x: 0.541}, zone: 'lower', protect: false}, // segments 68
  {id: 'S049', start: 111.861750, end: 112.612500, frames: [2682, 2700], portrait: {mode: 'fit'}, zone: 'lower', protect: true}, // segments 69
  {id: 'S050', start: 112.612500, end: 114.072292, frames: [2700, 2735], portrait: {mode: 'crop', x: 0.536}, zone: 'lower', protect: false}, // segments 70
  {id: 'S051', start: 114.072292, end: 122.622500, frames: [2735, 2940], portrait: {mode: 'fit'}, zone: 'lower', protect: true}, // segments 71,72,73
  {id: 'S052', start: 122.622500, end: 127.043583, frames: [2940, 3046], portrait: {mode: 'crop', x: 0.494}, zone: 'lower', protect: false}, // segments 74,75
  {id: 'S053', start: 127.043583, end: 128.044583, frames: [3046, 3070], portrait: {mode: 'crop', x: 0.531}, zone: 'lower', protect: false}, // segments 76
  {id: 'S054', start: 128.044583, end: 129.003875, frames: [3070, 3093], portrait: {mode: 'crop', x: 0.615}, zone: 'lower', protect: false}, // segments 77
  {id: 'S055', start: 129.003875, end: 129.963167, frames: [3093, 3116], portrait: {mode: 'crop', x: 0.507}, zone: 'lower', protect: false}, // segments 78
  {id: 'S056', start: 129.963167, end: 131.089292, frames: [3116, 3143], portrait: {mode: 'crop', x: 0.446}, zone: 'lower', protect: false}, // segments 79,80
  {id: 'S057', start: 131.089292, end: 131.339542, frames: [3143, 3149], portrait: {mode: 'crop', x: 0.462, x2: 0.4}, zone: 'lower', protect: false}, // segments 81
  {id: 'S058', start: 131.339542, end: 133.174708, frames: [3149, 3193], portrait: {mode: 'crop', x: 0.4}, zone: 'lower', protect: false}, // segments 82
  {id: 'S059', start: 133.174708, end: 135.802333, frames: [3193, 3256], portrait: {mode: 'fit'}, zone: 'upper', protect: true}, // segments 83
  {id: 'S060', start: 135.802333, end: 137.804333, frames: [3256, 3304], portrait: {mode: 'crop', x: 0.468}, zone: 'lower', protect: false}, // segments 84
  {id: 'S061', start: 137.804333, end: 138.721917, frames: [3304, 3326], portrait: {mode: 'crop', x: 0.615}, zone: 'lower', protect: false}, // segments 85
  {id: 'S062', start: 138.721917, end: 144.602792, frames: [3326, 3467], portrait: {mode: 'fit'}, zone: 'upper', protect: true}, // segments 86
  {id: 'S063', start: 144.602792, end: 147.647500, frames: [3467, 3540], portrait: {mode: 'crop', x: 0.626}, zone: 'lower', protect: false}, // segments 87
  {id: 'S064', start: 147.647500, end: 153.153000, frames: [3540, 3672], portrait: {mode: 'crop', x: 0.483}, zone: 'lower', protect: true}, // segments 88,89
  {id: 'S065', start: 153.153000, end: 156.156000, frames: [3672, 3744], portrait: {mode: 'crop', x: 0.467}, zone: 'lower', protect: false}, // segments 90,91,92
  {id: 'S066', start: 156.156000, end: 158.324833, frames: [3744, 3796], portrait: {mode: 'crop', x: 0.544}, zone: 'lower', protect: false}, // segments 93,94,95
  {id: 'S067', start: 158.324833, end: 159.659500, frames: [3796, 3828], portrait: {mode: 'crop', x: 0.591}, zone: 'lower', protect: false}, // segments 96,97
  {id: 'S068', start: 159.659500, end: 183.057875, frames: [3828, 4389], portrait: {mode: 'crop', x: 0.514}, zone: 'lower', protect: false}, // segments 98,99,100,101,102,103,104
  {id: 'S069', start: 183.057875, end: 184.767917, frames: [4389, 4430], portrait: {mode: 'crop', x: 0.472}, zone: 'lower', protect: true}, // segments 105
  {id: 'S070', start: 184.767917, end: 188.313125, frames: [4430, 4515], portrait: {mode: 'crop', x: 0.464}, zone: 'lower', protect: false}, // segments 106
  {id: 'S071', start: 188.313125, end: 188.813625, frames: [4515, 4527], portrait: {mode: 'crop', x: 0.532}, zone: 'lower', protect: false}, // segments 107
  {id: 'S072', start: 188.813625, end: 189.772917, frames: [4527, 4550], portrait: {mode: 'crop', x: 0.627}, zone: 'lower', protect: false}, // segments 108
  {id: 'S073', start: 189.772917, end: 192.567375, frames: [4550, 4617], portrait: {mode: 'crop', x: 0.586}, zone: 'lower', protect: false}, // segments 109
  {id: 'S074', start: 192.567375, end: 193.568375, frames: [4617, 4641], portrait: {mode: 'crop', x: 0.489}, zone: 'lower', protect: false}, // segments 110
  {id: 'S075', start: 193.568375, end: 194.319125, frames: [4641, 4659], portrait: {mode: 'crop', x: 0.437}, zone: 'lower', protect: false}, // segments 111
  {id: 'S076', start: 194.319125, end: 194.694500, frames: [4659, 4668], portrait: {mode: 'crop', x: 0.437, x2: 0.472}, zone: 'lower', protect: false}, // segments 112
  {id: 'S077', start: 194.694500, end: 197.030167, frames: [4668, 4724], portrait: {mode: 'crop', x: 0.472}, zone: 'lower', protect: false}, // segments 113,114
  {id: 'S078', start: 197.030167, end: 201.409542, frames: [4724, 4829], portrait: {mode: 'crop', x: 0.64}, zone: 'lower', protect: false}, // segments 115,116,117
  {id: 'S079', start: 201.409542, end: 205.538667, frames: [4829, 4928], portrait: {mode: 'fit'}, zone: 'bottom', protect: true}, // segments 118,119,120
  {id: 'S080', start: 205.538667, end: 210.084875, frames: [4928, 5037], portrait: {mode: 'crop', x: 0.578}, zone: 'lower', protect: false}, // segments 121,122
  {id: 'S081', start: 210.084875, end: 210.418542, frames: [5037, 5045], portrait: {mode: 'crop', x: 0.56, x2: 0.57}, zone: 'lower', protect: false}, // segments 123
  {id: 'S082', start: 210.418542, end: 222.722500, frames: [5045, 5340], portrait: {mode: 'crop', x: 0.57}, zone: 'lower', protect: false}, // segments 124,125,126,127
  {id: 'S083', start: 222.722500, end: 225.016458, frames: [5340, 5395], portrait: {mode: 'fit'}, zone: 'bottom', protect: true}, // segments 128
  {id: 'S084', start: 225.016458, end: 227.227000, frames: [5395, 5448], portrait: {mode: 'crop', x: 0.409}, zone: 'lower', protect: false}, // segments 129
  {id: 'S085', start: 227.227000, end: 229.979750, frames: [5448, 5514], portrait: {mode: 'crop', x: 0.541}, zone: 'lower', protect: false}, // segments 130
  {id: 'S086', start: 229.979750, end: 230.355125, frames: [5514, 5523], portrait: {mode: 'crop', x: 0.541, x2: 0.498}, zone: 'lower', protect: false}, // segments 131
  {id: 'S087', start: 230.355125, end: 231.814917, frames: [5523, 5558], portrait: {mode: 'crop', x: 0.498}, zone: 'lower', protect: false}, // segments 132
  {id: 'S088', start: 231.814917, end: 232.565667, frames: [5558, 5576], portrait: {mode: 'crop', x: 0.429}, zone: 'lower', protect: false}, // segments 133
  {id: 'S089', start: 232.565667, end: 235.985750, frames: [5576, 5658], portrait: {mode: 'crop', x: 0.493}, zone: 'lower', protect: false}, // segments 134,135
  {id: 'S090', start: 235.985750, end: 245.119875, frames: [5658, 5877], portrait: {mode: 'crop', x: 0.528}, zone: 'lower', protect: false}, // segments 136,137
  {id: 'S091', start: 245.119875, end: 252.418833, frames: [5877, 6052], portrait: {mode: 'crop', x: 0.469}, zone: 'lower', protect: false}, // segments 138,139,140
  {id: 'S092', start: 252.418833, end: 283.366417, frames: [6052, 6794], portrait: {mode: 'fit'}, zone: 'lower', protect: true}, // segments 141,142,143,144,145,146,147,148,149
];
